package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Approval generated by hbm2java
 */
public class Approval  implements java.io.Serializable {


     private BigDecimal approvalId;
     private BigDecimal approvalStatus;
     private Date approvalDate;
     private BigDecimal type;
     private BigDecimal projectId;
     private BigDecimal developerId;

    public Approval() {
    }

	
    public Approval(BigDecimal approvalId) {
        this.approvalId = approvalId;
    }
    public Approval(BigDecimal approvalId, BigDecimal approvalStatus, Date approvalDate, BigDecimal type, BigDecimal projectId, BigDecimal developerId) {
       this.approvalId = approvalId;
       this.approvalStatus = approvalStatus;
       this.approvalDate = approvalDate;
       this.type = type;
       this.projectId = projectId;
       this.developerId = developerId;
    }
   
    public BigDecimal getApprovalId() {
        return this.approvalId;
    }
    
    public void setApprovalId(BigDecimal approvalId) {
        this.approvalId = approvalId;
    }
    public BigDecimal getApprovalStatus() {
        return this.approvalStatus;
    }
    
    public void setApprovalStatus(BigDecimal approvalStatus) {
        this.approvalStatus = approvalStatus;
    }
    public Date getApprovalDate() {
        return this.approvalDate;
    }
    
    public void setApprovalDate(Date approvalDate) {
        this.approvalDate = approvalDate;
    }
    public BigDecimal getType() {
        return this.type;
    }
    
    public void setType(BigDecimal type) {
        this.type = type;
    }
    public BigDecimal getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(BigDecimal projectId) {
        this.projectId = projectId;
    }
    public BigDecimal getDeveloperId() {
        return this.developerId;
    }
    
    public void setDeveloperId(BigDecimal developerId) {
        this.developerId = developerId;
    }




}


