package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * CommunicationReport generated by hbm2java
 */
public class CommunicationReport  implements java.io.Serializable {


     private BigDecimal comId;
     private BigDecimal comPrjId;
     private String comType;
     private BigDecimal comParentType;
     private String comMethodTool;
     private String comWhen;
     private String comInformation;
     private String comResponsible;

    public CommunicationReport() {
    }

	
    public CommunicationReport(BigDecimal comId, BigDecimal comPrjId, String comType, BigDecimal comParentType) {
        this.comId = comId;
        this.comPrjId = comPrjId;
        this.comType = comType;
        this.comParentType = comParentType;
    }
    public CommunicationReport(BigDecimal comId, BigDecimal comPrjId, String comType, BigDecimal comParentType, String comMethodTool, String comWhen, String comInformation, String comResponsible) {
       this.comId = comId;
       this.comPrjId = comPrjId;
       this.comType = comType;
       this.comParentType = comParentType;
       this.comMethodTool = comMethodTool;
       this.comWhen = comWhen;
       this.comInformation = comInformation;
       this.comResponsible = comResponsible;
    }
   
    public BigDecimal getComId() {
        return this.comId;
    }
    
    public void setComId(BigDecimal comId) {
        this.comId = comId;
    }
    public BigDecimal getComPrjId() {
        return this.comPrjId;
    }
    
    public void setComPrjId(BigDecimal comPrjId) {
        this.comPrjId = comPrjId;
    }
    public String getComType() {
        return this.comType;
    }
    
    public void setComType(String comType) {
        this.comType = comType;
    }
    public BigDecimal getComParentType() {
        return this.comParentType;
    }
    
    public void setComParentType(BigDecimal comParentType) {
        this.comParentType = comParentType;
    }
    public String getComMethodTool() {
        return this.comMethodTool;
    }
    
    public void setComMethodTool(String comMethodTool) {
        this.comMethodTool = comMethodTool;
    }
    public String getComWhen() {
        return this.comWhen;
    }
    
    public void setComWhen(String comWhen) {
        this.comWhen = comWhen;
    }
    public String getComInformation() {
        return this.comInformation;
    }
    
    public void setComInformation(String comInformation) {
        this.comInformation = comInformation;
    }
    public String getComResponsible() {
        return this.comResponsible;
    }
    
    public void setComResponsible(String comResponsible) {
        this.comResponsible = comResponsible;
    }




}


