package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private BigDecimal customerId;
     private String cusName;
     private BigDecimal parentId;
     private String cusDescription;
     private String cusNote;
     private String og;

    public Customer() {
    }

	
    public Customer(BigDecimal customerId) {
        this.customerId = customerId;
    }
    public Customer(BigDecimal customerId, String cusName, BigDecimal parentId, String cusDescription, String cusNote, String og) {
       this.customerId = customerId;
       this.cusName = cusName;
       this.parentId = parentId;
       this.cusDescription = cusDescription;
       this.cusNote = cusNote;
       this.og = og;
    }
   
    public BigDecimal getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(BigDecimal customerId) {
        this.customerId = customerId;
    }
    public String getCusName() {
        return this.cusName;
    }
    
    public void setCusName(String cusName) {
        this.cusName = cusName;
    }
    public BigDecimal getParentId() {
        return this.parentId;
    }
    
    public void setParentId(BigDecimal parentId) {
        this.parentId = parentId;
    }
    public String getCusDescription() {
        return this.cusDescription;
    }
    
    public void setCusDescription(String cusDescription) {
        this.cusDescription = cusDescription;
    }
    public String getCusNote() {
        return this.cusNote;
    }
    
    public void setCusNote(String cusNote) {
        this.cusNote = cusNote;
    }
    public String getOg() {
        return this.og;
    }
    
    public void setOg(String og) {
        this.og = og;
    }




}


