package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Dependencies generated by hbm2java
 */
public class Dependencies  implements java.io.Serializable {


     private BigDecimal dependencyId;
     private BigDecimal projectPlanId;
     private String note;
     private Date actualDeliveryDate;
     private Date plannedDeliveryDate;
     private String item;

    public Dependencies() {
    }

	
    public Dependencies(BigDecimal dependencyId) {
        this.dependencyId = dependencyId;
    }
    public Dependencies(BigDecimal dependencyId, BigDecimal projectPlanId, String note, Date actualDeliveryDate, Date plannedDeliveryDate, String item) {
       this.dependencyId = dependencyId;
       this.projectPlanId = projectPlanId;
       this.note = note;
       this.actualDeliveryDate = actualDeliveryDate;
       this.plannedDeliveryDate = plannedDeliveryDate;
       this.item = item;
    }
   
    public BigDecimal getDependencyId() {
        return this.dependencyId;
    }
    
    public void setDependencyId(BigDecimal dependencyId) {
        this.dependencyId = dependencyId;
    }
    public BigDecimal getProjectPlanId() {
        return this.projectPlanId;
    }
    
    public void setProjectPlanId(BigDecimal projectPlanId) {
        this.projectPlanId = projectPlanId;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Date getActualDeliveryDate() {
        return this.actualDeliveryDate;
    }
    
    public void setActualDeliveryDate(Date actualDeliveryDate) {
        this.actualDeliveryDate = actualDeliveryDate;
    }
    public Date getPlannedDeliveryDate() {
        return this.plannedDeliveryDate;
    }
    
    public void setPlannedDeliveryDate(Date plannedDeliveryDate) {
        this.plannedDeliveryDate = plannedDeliveryDate;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }




}


