package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * EstDefect generated by hbm2java
 */
public class EstDefect  implements java.io.Serializable {


     private BigDecimal estDefectId;
     private BigDecimal projectId;
     private String reviewTest;
     private BigDecimal target;
     private String basicEst;

    public EstDefect() {
    }

	
    public EstDefect(BigDecimal estDefectId) {
        this.estDefectId = estDefectId;
    }
    public EstDefect(BigDecimal estDefectId, BigDecimal projectId, String reviewTest, BigDecimal target, String basicEst) {
       this.estDefectId = estDefectId;
       this.projectId = projectId;
       this.reviewTest = reviewTest;
       this.target = target;
       this.basicEst = basicEst;
    }
   
    public BigDecimal getEstDefectId() {
        return this.estDefectId;
    }
    
    public void setEstDefectId(BigDecimal estDefectId) {
        this.estDefectId = estDefectId;
    }
    public BigDecimal getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(BigDecimal projectId) {
        this.projectId = projectId;
    }
    public String getReviewTest() {
        return this.reviewTest;
    }
    
    public void setReviewTest(String reviewTest) {
        this.reviewTest = reviewTest;
    }
    public BigDecimal getTarget() {
        return this.target;
    }
    
    public void setTarget(BigDecimal target) {
        this.target = target;
    }
    public String getBasicEst() {
        return this.basicEst;
    }
    
    public void setBasicEst(String basicEst) {
        this.basicEst = basicEst;
    }




}


