package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * FinancialPlan generated by hbm2java
 */
public class FinancialPlan  implements java.io.Serializable {


     private BigDecimal invoiceScheduleId;
     private BigDecimal projectPlanId;
     private Date dueDate;
     private BigDecimal value;
     private String conditions;
     private String item;
     private Date actualDate;
     private BigDecimal type;

    public FinancialPlan() {
    }

	
    public FinancialPlan(BigDecimal invoiceScheduleId) {
        this.invoiceScheduleId = invoiceScheduleId;
    }
    public FinancialPlan(BigDecimal invoiceScheduleId, BigDecimal projectPlanId, Date dueDate, BigDecimal value, String conditions, String item, Date actualDate, BigDecimal type) {
       this.invoiceScheduleId = invoiceScheduleId;
       this.projectPlanId = projectPlanId;
       this.dueDate = dueDate;
       this.value = value;
       this.conditions = conditions;
       this.item = item;
       this.actualDate = actualDate;
       this.type = type;
    }
   
    public BigDecimal getInvoiceScheduleId() {
        return this.invoiceScheduleId;
    }
    
    public void setInvoiceScheduleId(BigDecimal invoiceScheduleId) {
        this.invoiceScheduleId = invoiceScheduleId;
    }
    public BigDecimal getProjectPlanId() {
        return this.projectPlanId;
    }
    
    public void setProjectPlanId(BigDecimal projectPlanId) {
        this.projectPlanId = projectPlanId;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public BigDecimal getValue() {
        return this.value;
    }
    
    public void setValue(BigDecimal value) {
        this.value = value;
    }
    public String getConditions() {
        return this.conditions;
    }
    
    public void setConditions(String conditions) {
        this.conditions = conditions;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public Date getActualDate() {
        return this.actualDate;
    }
    
    public void setActualDate(Date actualDate) {
        this.actualDate = actualDate;
    }
    public BigDecimal getType() {
        return this.type;
    }
    
    public void setType(BigDecimal type) {
        this.type = type;
    }




}


