package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * HolidayType generated by hbm2java
 */
public class HolidayType  implements java.io.Serializable {


     private String holidayTypeCode;
     private String description;
     private Set holidaies = new HashSet(0);

    public HolidayType() {
    }

	
    public HolidayType(String holidayTypeCode, String description) {
        this.holidayTypeCode = holidayTypeCode;
        this.description = description;
    }
    public HolidayType(String holidayTypeCode, String description, Set holidaies) {
       this.holidayTypeCode = holidayTypeCode;
       this.description = description;
       this.holidaies = holidaies;
    }
   
    public String getHolidayTypeCode() {
        return this.holidayTypeCode;
    }
    
    public void setHolidayTypeCode(String holidayTypeCode) {
        this.holidayTypeCode = holidayTypeCode;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getHolidaies() {
        return this.holidaies;
    }
    
    public void setHolidaies(Set holidaies) {
        this.holidaies = holidaies;
    }




}


