package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Interface generated by hbm2java
 */
public class Interface  implements java.io.Serializable {


     private BigDecimal interfaceId;
     private ProjectPlan projectPlan;
     private String name;
     private String position;
     private String responsibility;
     private String contact;
     private BigDecimal type;
     private BigDecimal assignToId;
     private BigDecimal roleId;
     private String communication;
     private String department;
     private String dependency;
     private String contactPerson;
     private String function;
     private String otherProjectName;
     private String contactAcc;

    public Interface() {
    }

	
    public Interface(BigDecimal interfaceId) {
        this.interfaceId = interfaceId;
    }
    public Interface(BigDecimal interfaceId, ProjectPlan projectPlan, String name, String position, String responsibility, String contact, BigDecimal type, BigDecimal assignToId, BigDecimal roleId, String communication, String department, String dependency, String contactPerson, String function, String otherProjectName, String contactAcc) {
       this.interfaceId = interfaceId;
       this.projectPlan = projectPlan;
       this.name = name;
       this.position = position;
       this.responsibility = responsibility;
       this.contact = contact;
       this.type = type;
       this.assignToId = assignToId;
       this.roleId = roleId;
       this.communication = communication;
       this.department = department;
       this.dependency = dependency;
       this.contactPerson = contactPerson;
       this.function = function;
       this.otherProjectName = otherProjectName;
       this.contactAcc = contactAcc;
    }
   
    public BigDecimal getInterfaceId() {
        return this.interfaceId;
    }
    
    public void setInterfaceId(BigDecimal interfaceId) {
        this.interfaceId = interfaceId;
    }
    public ProjectPlan getProjectPlan() {
        return this.projectPlan;
    }
    
    public void setProjectPlan(ProjectPlan projectPlan) {
        this.projectPlan = projectPlan;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public String getResponsibility() {
        return this.responsibility;
    }
    
    public void setResponsibility(String responsibility) {
        this.responsibility = responsibility;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public BigDecimal getType() {
        return this.type;
    }
    
    public void setType(BigDecimal type) {
        this.type = type;
    }
    public BigDecimal getAssignToId() {
        return this.assignToId;
    }
    
    public void setAssignToId(BigDecimal assignToId) {
        this.assignToId = assignToId;
    }
    public BigDecimal getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(BigDecimal roleId) {
        this.roleId = roleId;
    }
    public String getCommunication() {
        return this.communication;
    }
    
    public void setCommunication(String communication) {
        this.communication = communication;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getDependency() {
        return this.dependency;
    }
    
    public void setDependency(String dependency) {
        this.dependency = dependency;
    }
    public String getContactPerson() {
        return this.contactPerson;
    }
    
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }
    public String getFunction() {
        return this.function;
    }
    
    public void setFunction(String function) {
        this.function = function;
    }
    public String getOtherProjectName() {
        return this.otherProjectName;
    }
    
    public void setOtherProjectName(String otherProjectName) {
        this.otherProjectName = otherProjectName;
    }
    public String getContactAcc() {
        return this.contactAcc;
    }
    
    public void setContactAcc(String contactAcc) {
        this.contactAcc = contactAcc;
    }




}


