package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Iteration generated by hbm2java
 */
public class Iteration  implements java.io.Serializable {


     private BigDecimal iterationId;
     private Milestone milestone;
     private String description;
     private String milestone_1;
     private BigDecimal iteration;
     private Date planEndDate;
     private Date replanEndDate;
     private Date actualEndDate;

    public Iteration() {
    }

	
    public Iteration(BigDecimal iterationId) {
        this.iterationId = iterationId;
    }
    public Iteration(BigDecimal iterationId, Milestone milestone, String description, String milestone_1, BigDecimal iteration, Date planEndDate, Date replanEndDate, Date actualEndDate) {
       this.iterationId = iterationId;
       this.milestone = milestone;
       this.description = description;
       this.milestone_1 = milestone_1;
       this.iteration = iteration;
       this.planEndDate = planEndDate;
       this.replanEndDate = replanEndDate;
       this.actualEndDate = actualEndDate;
    }
   
    public BigDecimal getIterationId() {
        return this.iterationId;
    }
    
    public void setIterationId(BigDecimal iterationId) {
        this.iterationId = iterationId;
    }
    public Milestone getMilestone() {
        return this.milestone;
    }
    
    public void setMilestone(Milestone milestone) {
        this.milestone = milestone;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getMilestone_1() {
        return this.milestone_1;
    }
    
    public void setMilestone_1(String milestone_1) {
        this.milestone_1 = milestone_1;
    }
    public BigDecimal getIteration() {
        return this.iteration;
    }
    
    public void setIteration(BigDecimal iteration) {
        this.iteration = iteration;
    }
    public Date getPlanEndDate() {
        return this.planEndDate;
    }
    
    public void setPlanEndDate(Date planEndDate) {
        this.planEndDate = planEndDate;
    }
    public Date getReplanEndDate() {
        return this.replanEndDate;
    }
    
    public void setReplanEndDate(Date replanEndDate) {
        this.replanEndDate = replanEndDate;
    }
    public Date getActualEndDate() {
        return this.actualEndDate;
    }
    
    public void setActualEndDate(Date actualEndDate) {
        this.actualEndDate = actualEndDate;
    }




}


