package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * MetricDes generated by hbm2java
 */
public class MetricDes  implements java.io.Serializable {


     private String metricId;
     private Metricgroup metricgroup;
     private String metricName;
     private String unit;
     private Long displayIndex;
     private Long hotPriority;
     private String colorType;
     private String metricDesc;
     private BigDecimal id;

    public MetricDes() {
    }

	
    public MetricDes(String metricId, BigDecimal id) {
        this.metricId = metricId;
        this.id = id;
    }
    public MetricDes(String metricId, Metricgroup metricgroup, String metricName, String unit, Long displayIndex, Long hotPriority, String colorType, String metricDesc, BigDecimal id) {
       this.metricId = metricId;
       this.metricgroup = metricgroup;
       this.metricName = metricName;
       this.unit = unit;
       this.displayIndex = displayIndex;
       this.hotPriority = hotPriority;
       this.colorType = colorType;
       this.metricDesc = metricDesc;
       this.id = id;
    }
   
    public String getMetricId() {
        return this.metricId;
    }
    
    public void setMetricId(String metricId) {
        this.metricId = metricId;
    }
    public Metricgroup getMetricgroup() {
        return this.metricgroup;
    }
    
    public void setMetricgroup(Metricgroup metricgroup) {
        this.metricgroup = metricgroup;
    }
    public String getMetricName() {
        return this.metricName;
    }
    
    public void setMetricName(String metricName) {
        this.metricName = metricName;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public Long getDisplayIndex() {
        return this.displayIndex;
    }
    
    public void setDisplayIndex(Long displayIndex) {
        this.displayIndex = displayIndex;
    }
    public Long getHotPriority() {
        return this.hotPriority;
    }
    
    public void setHotPriority(Long hotPriority) {
        this.hotPriority = hotPriority;
    }
    public String getColorType() {
        return this.colorType;
    }
    
    public void setColorType(String colorType) {
        this.colorType = colorType;
    }
    public String getMetricDesc() {
        return this.metricDesc;
    }
    
    public void setMetricDesc(String metricDesc) {
        this.metricDesc = metricDesc;
    }
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }




}


