package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Ncview generated by hbm2java
 */
public class Ncview  implements java.io.Serializable {


     private BigDecimal viewid;
     private String title;
     private String fields;
     private String orderby;
     private String account;

    public Ncview() {
    }

	
    public Ncview(BigDecimal viewid, String account) {
        this.viewid = viewid;
        this.account = account;
    }
    public Ncview(BigDecimal viewid, String title, String fields, String orderby, String account) {
       this.viewid = viewid;
       this.title = title;
       this.fields = fields;
       this.orderby = orderby;
       this.account = account;
    }
   
    public BigDecimal getViewid() {
        return this.viewid;
    }
    
    public void setViewid(BigDecimal viewid) {
        this.viewid = viewid;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getFields() {
        return this.fields;
    }
    
    public void setFields(String fields) {
        this.fields = fields;
    }
    public String getOrderby() {
        return this.orderby;
    }
    
    public void setOrderby(String orderby) {
        this.orderby = orderby;
    }
    public String getAccount() {
        return this.account;
    }
    
    public void setAccount(String account) {
        this.account = account;
    }




}


