package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Normplan generated by hbm2java
 */
public class Normplan  implements java.io.Serializable {


     private BigDecimal normplanId;
     private Workunit workunit;
     private Lifecycle lifecycle;
     private Date endDate;
     private Date lastupdate;

    public Normplan() {
    }

	
    public Normplan(BigDecimal normplanId, Workunit workunit, Lifecycle lifecycle, Date endDate) {
        this.normplanId = normplanId;
        this.workunit = workunit;
        this.lifecycle = lifecycle;
        this.endDate = endDate;
    }
    public Normplan(BigDecimal normplanId, Workunit workunit, Lifecycle lifecycle, Date endDate, Date lastupdate) {
       this.normplanId = normplanId;
       this.workunit = workunit;
       this.lifecycle = lifecycle;
       this.endDate = endDate;
       this.lastupdate = lastupdate;
    }
   
    public BigDecimal getNormplanId() {
        return this.normplanId;
    }
    
    public void setNormplanId(BigDecimal normplanId) {
        this.normplanId = normplanId;
    }
    public Workunit getWorkunit() {
        return this.workunit;
    }
    
    public void setWorkunit(Workunit workunit) {
        this.workunit = workunit;
    }
    public Lifecycle getLifecycle() {
        return this.lifecycle;
    }
    
    public void setLifecycle(Lifecycle lifecycle) {
        this.lifecycle = lifecycle;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Date getLastupdate() {
        return this.lastupdate;
    }
    
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }




}


