package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Openissue generated by hbm2java
 */
public class Openissue  implements java.io.Serializable {


     private BigDecimal openissueId;
     private Project project;
     private Date startdate;
     private Date enddate;
     private String status;
     private String description;

    public Openissue() {
    }

	
    public Openissue(BigDecimal openissueId, Project project, String description) {
        this.openissueId = openissueId;
        this.project = project;
        this.description = description;
    }
    public Openissue(BigDecimal openissueId, Project project, Date startdate, Date enddate, String status, String description) {
       this.openissueId = openissueId;
       this.project = project;
       this.startdate = startdate;
       this.enddate = enddate;
       this.status = status;
       this.description = description;
    }
   
    public BigDecimal getOpenissueId() {
        return this.openissueId;
    }
    
    public void setOpenissueId(BigDecimal openissueId) {
        this.openissueId = openissueId;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


