package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * PlansQcStageId generated by hbm2java
 */
public class PlansQcStageId  implements java.io.Serializable {


     private BigDecimal qcid;
     private BigDecimal milestoneid;

    public PlansQcStageId() {
    }

    public PlansQcStageId(BigDecimal qcid, BigDecimal milestoneid) {
       this.qcid = qcid;
       this.milestoneid = milestoneid;
    }
   
    public BigDecimal getQcid() {
        return this.qcid;
    }
    
    public void setQcid(BigDecimal qcid) {
        this.qcid = qcid;
    }
    public BigDecimal getMilestoneid() {
        return this.milestoneid;
    }
    
    public void setMilestoneid(BigDecimal milestoneid) {
        this.milestoneid = milestoneid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlansQcStageId) ) return false;
		 PlansQcStageId castOther = ( PlansQcStageId ) other; 
         
		 return ( (this.getQcid()==castOther.getQcid()) || ( this.getQcid()!=null && castOther.getQcid()!=null && this.getQcid().equals(castOther.getQcid()) ) )
 && ( (this.getMilestoneid()==castOther.getMilestoneid()) || ( this.getMilestoneid()!=null && castOther.getMilestoneid()!=null && this.getMilestoneid().equals(castOther.getMilestoneid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getQcid() == null ? 0 : this.getQcid().hashCode() );
         result = 37 * result + ( getMilestoneid() == null ? 0 : this.getMilestoneid().hashCode() );
         return result;
   }   


}


