package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Practices generated by hbm2java
 */
public class Practices  implements java.io.Serializable {


     private BigDecimal practiceId;
     private Project project;
     private String scenario;
     private String practice;
     private BigDecimal type;
     private String category;

    public Practices() {
    }

	
    public Practices(BigDecimal practiceId, Project project) {
        this.practiceId = practiceId;
        this.project = project;
    }
    public Practices(BigDecimal practiceId, Project project, String scenario, String practice, BigDecimal type, String category) {
       this.practiceId = practiceId;
       this.project = project;
       this.scenario = scenario;
       this.practice = practice;
       this.type = type;
       this.category = category;
    }
   
    public BigDecimal getPracticeId() {
        return this.practiceId;
    }
    
    public void setPracticeId(BigDecimal practiceId) {
        this.practiceId = practiceId;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public String getScenario() {
        return this.scenario;
    }
    
    public void setScenario(String scenario) {
        this.scenario = scenario;
    }
    public String getPractice() {
        return this.practice;
    }
    
    public void setPractice(String practice) {
        this.practice = practice;
    }
    public BigDecimal getType() {
        return this.type;
    }
    
    public void setType(BigDecimal type) {
        this.type = type;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }




}


