package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ProjectTailoring generated by hbm2java
 */
public class ProjectTailoring  implements java.io.Serializable {


     private ProjectTailoringId id;
     private Tailoring tailoring;
     private BigDecimal action;
     private String note;

    public ProjectTailoring() {
    }

	
    public ProjectTailoring(ProjectTailoringId id, Tailoring tailoring, BigDecimal action) {
        this.id = id;
        this.tailoring = tailoring;
        this.action = action;
    }
    public ProjectTailoring(ProjectTailoringId id, Tailoring tailoring, BigDecimal action, String note) {
       this.id = id;
       this.tailoring = tailoring;
       this.action = action;
       this.note = note;
    }
   
    public ProjectTailoringId getId() {
        return this.id;
    }
    
    public void setId(ProjectTailoringId id) {
        this.id = id;
    }
    public Tailoring getTailoring() {
        return this.tailoring;
    }
    
    public void setTailoring(Tailoring tailoring) {
        this.tailoring = tailoring;
    }
    public BigDecimal getAction() {
        return this.action;
    }
    
    public void setAction(BigDecimal action) {
        this.action = action;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


