package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ReferenceData generated by hbm2java
 */
public class ReferenceData  implements java.io.Serializable {


     private BigDecimal referenceId;
     private LanguageCode languageCode;
     private String groupCode;
     private String itemCode;
     private String description;
     private Byte disabled;

    public ReferenceData() {
    }

	
    public ReferenceData(BigDecimal referenceId) {
        this.referenceId = referenceId;
    }
    public ReferenceData(BigDecimal referenceId, LanguageCode languageCode, String groupCode, String itemCode, String description, Byte disabled) {
       this.referenceId = referenceId;
       this.languageCode = languageCode;
       this.groupCode = groupCode;
       this.itemCode = itemCode;
       this.description = description;
       this.disabled = disabled;
    }
   
    public BigDecimal getReferenceId() {
        return this.referenceId;
    }
    
    public void setReferenceId(BigDecimal referenceId) {
        this.referenceId = referenceId;
    }
    public LanguageCode getLanguageCode() {
        return this.languageCode;
    }
    
    public void setLanguageCode(LanguageCode languageCode) {
        this.languageCode = languageCode;
    }
    public String getGroupCode() {
        return this.groupCode;
    }
    
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }
    public String getItemCode() {
        return this.itemCode;
    }
    
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Byte getDisabled() {
        return this.disabled;
    }
    
    public void setDisabled(Byte disabled) {
        this.disabled = disabled;
    }




}


