package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * References generated by hbm2java
 */
public class References  implements java.io.Serializable {


     private BigDecimal referenceId;
     private ProjectPlan projectPlan;
     private Date issuedDate;
     private String source;
     private String note;
     private String document;

    public References() {
    }

	
    public References(BigDecimal referenceId) {
        this.referenceId = referenceId;
    }
    public References(BigDecimal referenceId, ProjectPlan projectPlan, Date issuedDate, String source, String note, String document) {
       this.referenceId = referenceId;
       this.projectPlan = projectPlan;
       this.issuedDate = issuedDate;
       this.source = source;
       this.note = note;
       this.document = document;
    }
   
    public BigDecimal getReferenceId() {
        return this.referenceId;
    }
    
    public void setReferenceId(BigDecimal referenceId) {
        this.referenceId = referenceId;
    }
    public ProjectPlan getProjectPlan() {
        return this.projectPlan;
    }
    
    public void setProjectPlan(ProjectPlan projectPlan) {
        this.projectPlan = projectPlan;
    }
    public Date getIssuedDate() {
        return this.issuedDate;
    }
    
    public void setIssuedDate(Date issuedDate) {
        this.issuedDate = issuedDate;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getDocument() {
        return this.document;
    }
    
    public void setDocument(String document) {
        this.document = document;
    }




}


