package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ReqChangesMng generated by hbm2java
 */
public class ReqChangesMng  implements java.io.Serializable {


     private BigDecimal reqChangesId;
     private BigDecimal reqProjectId;
     private String reqChangesDesc;
     private String reqCreator;
     private String reqReviewer;
     private String reqAprover;
     private String reqLogLocation;

    public ReqChangesMng() {
    }

	
    public ReqChangesMng(BigDecimal reqChangesId, BigDecimal reqProjectId, String reqCreator, String reqReviewer, String reqAprover, String reqLogLocation) {
        this.reqChangesId = reqChangesId;
        this.reqProjectId = reqProjectId;
        this.reqCreator = reqCreator;
        this.reqReviewer = reqReviewer;
        this.reqAprover = reqAprover;
        this.reqLogLocation = reqLogLocation;
    }
    public ReqChangesMng(BigDecimal reqChangesId, BigDecimal reqProjectId, String reqChangesDesc, String reqCreator, String reqReviewer, String reqAprover, String reqLogLocation) {
       this.reqChangesId = reqChangesId;
       this.reqProjectId = reqProjectId;
       this.reqChangesDesc = reqChangesDesc;
       this.reqCreator = reqCreator;
       this.reqReviewer = reqReviewer;
       this.reqAprover = reqAprover;
       this.reqLogLocation = reqLogLocation;
    }
   
    public BigDecimal getReqChangesId() {
        return this.reqChangesId;
    }
    
    public void setReqChangesId(BigDecimal reqChangesId) {
        this.reqChangesId = reqChangesId;
    }
    public BigDecimal getReqProjectId() {
        return this.reqProjectId;
    }
    
    public void setReqProjectId(BigDecimal reqProjectId) {
        this.reqProjectId = reqProjectId;
    }
    public String getReqChangesDesc() {
        return this.reqChangesDesc;
    }
    
    public void setReqChangesDesc(String reqChangesDesc) {
        this.reqChangesDesc = reqChangesDesc;
    }
    public String getReqCreator() {
        return this.reqCreator;
    }
    
    public void setReqCreator(String reqCreator) {
        this.reqCreator = reqCreator;
    }
    public String getReqReviewer() {
        return this.reqReviewer;
    }
    
    public void setReqReviewer(String reqReviewer) {
        this.reqReviewer = reqReviewer;
    }
    public String getReqAprover() {
        return this.reqAprover;
    }
    
    public void setReqAprover(String reqAprover) {
        this.reqAprover = reqAprover;
    }
    public String getReqLogLocation() {
        return this.reqLogLocation;
    }
    
    public void setReqLogLocation(String reqLogLocation) {
        this.reqLogLocation = reqLogLocation;
    }




}


