package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Staffs generated by hbm2java
 */
public class Staffs  implements java.io.Serializable {


     private long code;
     private String fullName;
     private Date joinDate;
     private Date leaveDate;
     private String groupId;
     private String type;

    public Staffs() {
    }

	
    public Staffs(long code) {
        this.code = code;
    }
    public Staffs(long code, String fullName, Date joinDate, Date leaveDate, String groupId, String type) {
       this.code = code;
       this.fullName = fullName;
       this.joinDate = joinDate;
       this.leaveDate = leaveDate;
       this.groupId = groupId;
       this.type = type;
    }
   
    public long getCode() {
        return this.code;
    }
    
    public void setCode(long code) {
        this.code = code;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }
    public Date getLeaveDate() {
        return this.leaveDate;
    }
    
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


