package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TeamEvaluation generated by hbm2java
 */
public class TeamEvaluation  implements java.io.Serializable {


     private BigDecimal teamEvaluationId;
     private BigDecimal projectId;
     private BigDecimal developerId;
     private String role;
     private String effect;
     private BigDecimal cost;
     private String note;

    public TeamEvaluation() {
    }

	
    public TeamEvaluation(BigDecimal teamEvaluationId, BigDecimal projectId, BigDecimal developerId) {
        this.teamEvaluationId = teamEvaluationId;
        this.projectId = projectId;
        this.developerId = developerId;
    }
    public TeamEvaluation(BigDecimal teamEvaluationId, BigDecimal projectId, BigDecimal developerId, String role, String effect, BigDecimal cost, String note) {
       this.teamEvaluationId = teamEvaluationId;
       this.projectId = projectId;
       this.developerId = developerId;
       this.role = role;
       this.effect = effect;
       this.cost = cost;
       this.note = note;
    }
   
    public BigDecimal getTeamEvaluationId() {
        return this.teamEvaluationId;
    }
    
    public void setTeamEvaluationId(BigDecimal teamEvaluationId) {
        this.teamEvaluationId = teamEvaluationId;
    }
    public BigDecimal getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(BigDecimal projectId) {
        this.projectId = projectId;
    }
    public BigDecimal getDeveloperId() {
        return this.developerId;
    }
    
    public void setDeveloperId(BigDecimal developerId) {
        this.developerId = developerId;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getEffect() {
        return this.effect;
    }
    
    public void setEffect(String effect) {
        this.effect = effect;
    }
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


