package openones.oopms.planner.model;
// Generated Jul 6, 2012 2:03:21 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * Stage generated by hbm2java
 */
public class Stage implements java.io.Serializable {

    private BigDecimal stageId;
    private String name;

    public Stage() {
    }

    public Stage(BigDecimal stageId, String name) {
        this.stageId = stageId;
        this.name = name;
    }

    public BigDecimal getStageId() {
        return this.stageId;
    }

    public void setStageId(BigDecimal stageId) {
        this.stageId = stageId;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
