package openones.oopms.planner.model;
// Generated Jul 12, 2012 4:48:19 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * Tasks generated by hbm2java
 */
public class Tasks implements java.io.Serializable {

    private BigDecimal taskid;
    private String taskname;
    private BigDecimal statusId;
    private BigDecimal developerid;
    private BigDecimal stageid;
    private BigDecimal product;
    private BigDecimal productsize;
    private BigDecimal completenessstatus;
    private Date startdate;
    private Date plannedenddate;
    private Date enddate;
    private BigDecimal plannedeffort;
    private BigDecimal currenteffort;
    private BigDecimal actualeffort;
    private String description;
    private BigDecimal projectid;
    private Boolean active;
    private BigDecimal processId;

    private String status_str;
    private String product_str;
    private String stage_str;
    private String process_str;
    private String developer_str;
    private String project_str;

    /**
     * Get value of developer_str.
     * @return the developer_str
     */
    public String getDeveloper_str() {
        return developer_str;
    }

    /**
     * Set the value for developer_str.
     * @param developer_str the developer_str to set
     */
    public void setDeveloper_str(String developer_str) {
        this.developer_str = developer_str;
    }

    public Tasks() {
        taskid = new BigDecimal("0");
        taskname = " ";
        startdate = new Date();
        plannedenddate = new Date();
        plannedeffort = new BigDecimal("0");
        currenteffort = new BigDecimal("0");
        actualeffort = new BigDecimal("0");
        description = "no thing";
        stageid = new BigDecimal("0");
        processId = new BigDecimal("0");
        product = new BigDecimal("0");
        developerid = new BigDecimal("0");
        statusId = new BigDecimal("0");
        productsize = new BigDecimal("0");
        completenessstatus = new BigDecimal("0");
        active = true;
    }

    public Tasks(BigDecimal taskid) {
        this.taskid = taskid;
    }
    public Tasks(BigDecimal taskid, String taskname, BigDecimal statusId, BigDecimal developerid, BigDecimal stageid,
            BigDecimal product, BigDecimal productsize, BigDecimal completenessstatus, Date startdate,
            Date plannedenddate, Date enddate, BigDecimal plannedeffort, BigDecimal actualeffort, String description,
            BigDecimal projectid, Boolean active, BigDecimal processId) {
        this.taskid = taskid;
        this.taskname = taskname;
        this.statusId = statusId;
        this.developerid = developerid;
        this.stageid = stageid;
        this.product = product;
        this.productsize = productsize;
        this.completenessstatus = completenessstatus;
        this.startdate = startdate;
        this.plannedenddate = plannedenddate;
        this.enddate = enddate;
        this.plannedeffort = plannedeffort;
        this.actualeffort = actualeffort;
        this.description = description;
        this.projectid = projectid;
        this.active = active;
        this.processId = processId;
    }

    public BigDecimal getTaskid() {
        return this.taskid;
    }

    public void setTaskid(BigDecimal taskid) {
        this.taskid = taskid;
    }

    public String getTaskname() {
        return this.taskname;
    }

    public void setTaskname(String taskname) {
        this.taskname = taskname;
    }
    public BigDecimal getStatusId() {
        return this.statusId;
    }

    public void setStatusId(BigDecimal statusId) {
        this.statusId = statusId;
    }
    public BigDecimal getDeveloperid() {
        return this.developerid;
    }

    public void setDeveloperid(BigDecimal developerid) {
        this.developerid = developerid;
    }
    public BigDecimal getStageid() {
        return this.stageid;
    }

    public void setStageid(BigDecimal stageid) {
        this.stageid = stageid;
    }
    public BigDecimal getProduct() {
        return this.product;
    }

    public void setProduct(BigDecimal product) {
        this.product = product;
    }
    public BigDecimal getProductsize() {
        return this.productsize;
    }

    public void setProductsize(BigDecimal productsize) {
        this.productsize = productsize;
    }
    public BigDecimal getCompletenessstatus() {
        return this.completenessstatus;
    }

    public void setCompletenessstatus(BigDecimal completenessstatus) {
        this.completenessstatus = completenessstatus;
    }
    public Date getStartdate() {
        return this.startdate;
    }

    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getPlannedenddate() {
        return this.plannedenddate;
    }

    public void setPlannedenddate(Date plannedenddate) {
        this.plannedenddate = plannedenddate;
    }
    public Date getEnddate() {
        return this.enddate;
    }

    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public BigDecimal getPlannedeffort() {
        return this.plannedeffort;
    }

    public void setPlannedeffort(BigDecimal plannedeffort) {
        this.plannedeffort = plannedeffort;
    }
    public BigDecimal getActualeffort() {
        return this.actualeffort;
    }

    public void setActualeffort(BigDecimal actualeffort) {
        this.actualeffort = actualeffort;
    }
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getProjectid() {
        return this.projectid;
    }

    public void setProjectid(BigDecimal projectid) {
        this.projectid = projectid;
    }
    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }
    public BigDecimal getProcessId() {
        return this.processId;
    }

    public void setProcessId(BigDecimal processId) {
        this.processId = processId;
    }

    /**
     * Get value of status_str.
     * @return the status_str
     */
    public String getStatus_str() {
        return status_str;
    }

    /**
     * Set the value for status_str.
     * @param status_str the status_str to set
     */
    public void setStatus_str(String status_str) {
        this.status_str = status_str;
    }

    /**
     * Get value of product_str.
     * @return the product_str
     */
    public String getProduct_str() {
        return product_str;
    }

    /**
     * Set the value for product_str.
     * @param product_str the product_str to set
     */
    public void setProduct_str(String product_str) {
        this.product_str = product_str;
    }

    /**
     * Get value of stage_str.
     * @return the stage_str
     */
    public String getStage_str() {
        return stage_str;
    }

    /**
     * Set the value for stage_str.
     * @param stage_str the stage_str to set
     */
    public void setStage_str(String stage_str) {
        this.stage_str = stage_str;
    }

    /**
     * Get value of process_str.
     * @return the process_str
     */
    public String getProcess_str() {
        return process_str;
    }

    /**
     * Set the value for process_str.
     * @param process_str the process_str to set
     */
    public void setProcess_str(String process_str) {
        this.process_str = process_str;
    }

    /**
     * Get value of project_str.
     * @return the project_str
     */
    public String getProject_str() {
        return project_str;
    }

    /**
     * Set the value for project_str.
     * @param project_str the project_str to set
     */
    public void setProject_str(String project_str) {
        this.project_str = project_str;
    }

    /**
     * Get value of currenteffort.
     * @return the currenteffort
     */
    public BigDecimal getCurrenteffort() {
        return currenteffort;
    }

    /**
     * Set the value for currenteffort.
     * @param currenteffort the currenteffort to set
     */
    public void setCurrenteffort(BigDecimal currenteffort) {
        this.currenteffort = currenteffort;
    }

}
