package openones.oopms.planner.model;
// Generated Aug 4, 2012 9:40:23 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * LanguageCode generated by hbm2java
 */
public class LanguageCode  implements java.io.Serializable {


     private String langCode;
     private String description;
     private Set generalReferences = new HashSet(0);

    public LanguageCode() {
    }

	
    public LanguageCode(String langCode) {
        this.langCode = langCode;
    }
    public LanguageCode(String langCode, String description, Set generalReferences) {
       this.langCode = langCode;
       this.description = description;
       this.generalReferences = generalReferences;
    }
   
    public String getLangCode() {
        return this.langCode;
    }
    
    public void setLangCode(String langCode) {
        this.langCode = langCode;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getGeneralReferences() {
        return this.generalReferences;
    }
    
    public void setGeneralReferences(Set generalReferences) {
        this.generalReferences = generalReferences;
    }




}


