package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ArchiveActualEffortByType generated by hbm2java
 */
public class ArchiveActualEffortByType  implements java.io.Serializable {


     private ArchiveActualEffortByTypeId id;
     private BigDecimal actualEffort;

    public ArchiveActualEffortByType() {
    }

    public ArchiveActualEffortByType(ArchiveActualEffortByTypeId id, BigDecimal actualEffort) {
       this.id = id;
       this.actualEffort = actualEffort;
    }
   
    public ArchiveActualEffortByTypeId getId() {
        return this.id;
    }
    
    public void setId(ArchiveActualEffortByTypeId id) {
        this.id = id;
    }
    public BigDecimal getActualEffort() {
        return this.actualEffort;
    }
    
    public void setActualEffort(BigDecimal actualEffort) {
        this.actualEffort = actualEffort;
    }




}


