package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ArchiveActualEffortByTypeId generated by hbm2java
 */
public class ArchiveActualEffortByTypeId  implements java.io.Serializable {


     private BigDecimal projectId;
     private BigDecimal typeofworkId;

    public ArchiveActualEffortByTypeId() {
    }

    public ArchiveActualEffortByTypeId(BigDecimal projectId, BigDecimal typeofworkId) {
       this.projectId = projectId;
       this.typeofworkId = typeofworkId;
    }
   
    public BigDecimal getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(BigDecimal projectId) {
        this.projectId = projectId;
    }
    public BigDecimal getTypeofworkId() {
        return this.typeofworkId;
    }
    
    public void setTypeofworkId(BigDecimal typeofworkId) {
        this.typeofworkId = typeofworkId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArchiveActualEffortByTypeId) ) return false;
		 ArchiveActualEffortByTypeId castOther = ( ArchiveActualEffortByTypeId ) other; 
         
		 return ( (this.getProjectId()==castOther.getProjectId()) || ( this.getProjectId()!=null && castOther.getProjectId()!=null && this.getProjectId().equals(castOther.getProjectId()) ) )
 && ( (this.getTypeofworkId()==castOther.getTypeofworkId()) || ( this.getTypeofworkId()!=null && castOther.getTypeofworkId()!=null && this.getTypeofworkId().equals(castOther.getTypeofworkId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProjectId() == null ? 0 : this.getProjectId().hashCode() );
         result = 37 * result + ( getTypeofworkId() == null ? 0 : this.getTypeofworkId().hashCode() );
         return result;
   }   


}


