package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * DarPlan generated by hbm2java
 */
public class DarPlan  implements java.io.Serializable {


     private BigDecimal darPlanId;
     private Developer developer;
     private Project project;
     private String darItem;
     private Date planDate;
     private Date actualDate;
     private String darCause;

    public DarPlan() {
    }

	
    public DarPlan(BigDecimal darPlanId, Project project, String darItem, Date planDate) {
        this.darPlanId = darPlanId;
        this.project = project;
        this.darItem = darItem;
        this.planDate = planDate;
    }
    public DarPlan(BigDecimal darPlanId, Developer developer, Project project, String darItem, Date planDate, Date actualDate, String darCause) {
       this.darPlanId = darPlanId;
       this.developer = developer;
       this.project = project;
       this.darItem = darItem;
       this.planDate = planDate;
       this.actualDate = actualDate;
       this.darCause = darCause;
    }
   
    public BigDecimal getDarPlanId() {
        return this.darPlanId;
    }
    
    public void setDarPlanId(BigDecimal darPlanId) {
        this.darPlanId = darPlanId;
    }
    public Developer getDeveloper() {
        return this.developer;
    }
    
    public void setDeveloper(Developer developer) {
        this.developer = developer;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public String getDarItem() {
        return this.darItem;
    }
    
    public void setDarItem(String darItem) {
        this.darItem = darItem;
    }
    public Date getPlanDate() {
        return this.planDate;
    }
    
    public void setPlanDate(Date planDate) {
        this.planDate = planDate;
    }
    public Date getActualDate() {
        return this.actualDate;
    }
    
    public void setActualDate(Date actualDate) {
        this.actualDate = actualDate;
    }
    public String getDarCause() {
        return this.darCause;
    }
    
    public void setDarCause(String darCause) {
        this.darCause = darCause;
    }




}


