package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * DefectPermissionId generated by hbm2java
 */
public class DefectPermissionId  implements java.io.Serializable {


     private BigDecimal projectId;
     private BigDecimal developerId;

    public DefectPermissionId() {
    }

    public DefectPermissionId(BigDecimal projectId, BigDecimal developerId) {
       this.projectId = projectId;
       this.developerId = developerId;
    }
   
    public BigDecimal getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(BigDecimal projectId) {
        this.projectId = projectId;
    }
    public BigDecimal getDeveloperId() {
        return this.developerId;
    }
    
    public void setDeveloperId(BigDecimal developerId) {
        this.developerId = developerId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DefectPermissionId) ) return false;
		 DefectPermissionId castOther = ( DefectPermissionId ) other; 
         
		 return ( (this.getProjectId()==castOther.getProjectId()) || ( this.getProjectId()!=null && castOther.getProjectId()!=null && this.getProjectId().equals(castOther.getProjectId()) ) )
 && ( (this.getDeveloperId()==castOther.getDeveloperId()) || ( this.getDeveloperId()!=null && castOther.getDeveloperId()!=null && this.getDeveloperId().equals(castOther.getDeveloperId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProjectId() == null ? 0 : this.getProjectId().hashCode() );
         result = 37 * result + ( getDeveloperId() == null ? 0 : this.getDeveloperId().hashCode() );
         return result;
   }   


}


