package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA



/**
 * DefectPermission generated by hbm2java
 */
public class DefectPermission  implements java.io.Serializable {


     private DefectPermissionId id;
     private String status;
     private String position;

    public DefectPermission() {
    }

    public DefectPermission(DefectPermissionId id, String status, String position) {
       this.id = id;
       this.status = status;
       this.position = position;
    }
   
    public DefectPermissionId getId() {
        return this.id;
    }
    
    public void setId(DefectPermissionId id) {
        this.id = id;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }




}


