package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Holiday generated by hbm2java
 */
public class Holiday  implements java.io.Serializable {


     private BigDecimal holidayId;
     private HolidayType holidayType;
     private Date holidayStartDate;
     private Date holidayEndDate;
     private String description;
     private Byte isFulltime;
     private Byte disabled;

    public Holiday() {
    }

	
    public Holiday(BigDecimal holidayId) {
        this.holidayId = holidayId;
    }
    public Holiday(BigDecimal holidayId, HolidayType holidayType, Date holidayStartDate, Date holidayEndDate, String description, Byte isFulltime, Byte disabled) {
       this.holidayId = holidayId;
       this.holidayType = holidayType;
       this.holidayStartDate = holidayStartDate;
       this.holidayEndDate = holidayEndDate;
       this.description = description;
       this.isFulltime = isFulltime;
       this.disabled = disabled;
    }
   
    public BigDecimal getHolidayId() {
        return this.holidayId;
    }
    
    public void setHolidayId(BigDecimal holidayId) {
        this.holidayId = holidayId;
    }
    public HolidayType getHolidayType() {
        return this.holidayType;
    }
    
    public void setHolidayType(HolidayType holidayType) {
        this.holidayType = holidayType;
    }
    public Date getHolidayStartDate() {
        return this.holidayStartDate;
    }
    
    public void setHolidayStartDate(Date holidayStartDate) {
        this.holidayStartDate = holidayStartDate;
    }
    public Date getHolidayEndDate() {
        return this.holidayEndDate;
    }
    
    public void setHolidayEndDate(Date holidayEndDate) {
        this.holidayEndDate = holidayEndDate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Byte getIsFulltime() {
        return this.isFulltime;
    }
    
    public void setIsFulltime(Byte isFulltime) {
        this.isFulltime = isFulltime;
    }
    public Byte getDisabled() {
        return this.disabled;
    }
    
    public void setDisabled(Byte disabled) {
        this.disabled = disabled;
    }




}


