package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * OtherAssignment generated by hbm2java
 */
public class OtherAssignment  implements java.io.Serializable {


     private BigDecimal oaId;
     private Developer developer;
     private byte type;
     private Date fromDate;
     private Date endDate;
     private String description;
     private BigDecimal usage;

    public OtherAssignment() {
    }

	
    public OtherAssignment(BigDecimal oaId, Developer developer, byte type, Date fromDate, Date endDate) {
        this.oaId = oaId;
        this.developer = developer;
        this.type = type;
        this.fromDate = fromDate;
        this.endDate = endDate;
    }
    public OtherAssignment(BigDecimal oaId, Developer developer, byte type, Date fromDate, Date endDate, String description, BigDecimal usage) {
       this.oaId = oaId;
       this.developer = developer;
       this.type = type;
       this.fromDate = fromDate;
       this.endDate = endDate;
       this.description = description;
       this.usage = usage;
    }
   
    public BigDecimal getOaId() {
        return this.oaId;
    }
    
    public void setOaId(BigDecimal oaId) {
        this.oaId = oaId;
    }
    public Developer getDeveloper() {
        return this.developer;
    }
    
    public void setDeveloper(Developer developer) {
        this.developer = developer;
    }
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getUsage() {
        return this.usage;
    }
    
    public void setUsage(BigDecimal usage) {
        this.usage = usage;
    }




}


