package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Planning generated by hbm2java
 */
public class Planning  implements java.io.Serializable {


     private BigDecimal planningId;
     private BigDecimal version;
     private Workunit workunit;
     private BigDecimal year;
     private Date lastupdate;

    public Planning() {
    }

	
    public Planning(BigDecimal planningId, Workunit workunit, BigDecimal year) {
        this.planningId = planningId;
        this.workunit = workunit;
        this.year = year;
    }
    public Planning(BigDecimal planningId, Workunit workunit, BigDecimal year, Date lastupdate) {
       this.planningId = planningId;
       this.workunit = workunit;
       this.year = year;
       this.lastupdate = lastupdate;
    }
   
    public BigDecimal getPlanningId() {
        return this.planningId;
    }
    
    public void setPlanningId(BigDecimal planningId) {
        this.planningId = planningId;
    }
    public BigDecimal getVersion() {
        return this.version;
    }
    
    public void setVersion(BigDecimal version) {
        this.version = version;
    }
    public Workunit getWorkunit() {
        return this.workunit;
    }
    
    public void setWorkunit(Workunit workunit) {
        this.workunit = workunit;
    }
    public BigDecimal getYear() {
        return this.year;
    }
    
    public void setYear(BigDecimal year) {
        this.year = year;
    }
    public Date getLastupdate() {
        return this.lastupdate;
    }
    
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }




}


