package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ProjectArchive generated by hbm2java
 */
public class ProjectArchive  implements java.io.Serializable {


     private BigDecimal projectId;
     private BigDecimal actualMaxTeamSize;
     private BigDecimal actualEffortUsage;
     private BigDecimal billableActualEffort;
     private BigDecimal actualManagement;
     private BigDecimal actualManEffort;
     private BigDecimal actualDevEffort;
     private BigDecimal correctionCost;
     private BigDecimal transCost;
     private BigDecimal actualEffort;
     private BigDecimal totalReqCommittedSize;
     private BigDecimal totalReqDesignedSize;
     private BigDecimal totalReqCoded;
     private BigDecimal requirementStability;
     private BigDecimal totalReqTestedSize;
     private BigDecimal totalRequirementSize;
     private BigDecimal totalReqDeployedSize;
     private BigDecimal averageReqResponseTime;
     private BigDecimal totalAcceptedSize;
     private String requirementGraphicsValue;
     private String requirementGraphicsName;

    public ProjectArchive() {
    }

	
    public ProjectArchive(BigDecimal projectId) {
        this.projectId = projectId;
    }
    public ProjectArchive(BigDecimal projectId, BigDecimal actualMaxTeamSize, BigDecimal actualEffortUsage, BigDecimal billableActualEffort, BigDecimal actualManagement, BigDecimal actualManEffort, BigDecimal actualDevEffort, BigDecimal correctionCost, BigDecimal transCost, BigDecimal actualEffort, BigDecimal totalReqCommittedSize, BigDecimal totalReqDesignedSize, BigDecimal totalReqCoded, BigDecimal requirementStability, BigDecimal totalReqTestedSize, BigDecimal totalRequirementSize, BigDecimal totalReqDeployedSize, BigDecimal averageReqResponseTime, BigDecimal totalAcceptedSize, String requirementGraphicsValue, String requirementGraphicsName) {
       this.projectId = projectId;
       this.actualMaxTeamSize = actualMaxTeamSize;
       this.actualEffortUsage = actualEffortUsage;
       this.billableActualEffort = billableActualEffort;
       this.actualManagement = actualManagement;
       this.actualManEffort = actualManEffort;
       this.actualDevEffort = actualDevEffort;
       this.correctionCost = correctionCost;
       this.transCost = transCost;
       this.actualEffort = actualEffort;
       this.totalReqCommittedSize = totalReqCommittedSize;
       this.totalReqDesignedSize = totalReqDesignedSize;
       this.totalReqCoded = totalReqCoded;
       this.requirementStability = requirementStability;
       this.totalReqTestedSize = totalReqTestedSize;
       this.totalRequirementSize = totalRequirementSize;
       this.totalReqDeployedSize = totalReqDeployedSize;
       this.averageReqResponseTime = averageReqResponseTime;
       this.totalAcceptedSize = totalAcceptedSize;
       this.requirementGraphicsValue = requirementGraphicsValue;
       this.requirementGraphicsName = requirementGraphicsName;
    }
   
    public BigDecimal getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(BigDecimal projectId) {
        this.projectId = projectId;
    }
    public BigDecimal getActualMaxTeamSize() {
        return this.actualMaxTeamSize;
    }
    
    public void setActualMaxTeamSize(BigDecimal actualMaxTeamSize) {
        this.actualMaxTeamSize = actualMaxTeamSize;
    }
    public BigDecimal getActualEffortUsage() {
        return this.actualEffortUsage;
    }
    
    public void setActualEffortUsage(BigDecimal actualEffortUsage) {
        this.actualEffortUsage = actualEffortUsage;
    }
    public BigDecimal getBillableActualEffort() {
        return this.billableActualEffort;
    }
    
    public void setBillableActualEffort(BigDecimal billableActualEffort) {
        this.billableActualEffort = billableActualEffort;
    }
    public BigDecimal getActualManagement() {
        return this.actualManagement;
    }
    
    public void setActualManagement(BigDecimal actualManagement) {
        this.actualManagement = actualManagement;
    }
    public BigDecimal getActualManEffort() {
        return this.actualManEffort;
    }
    
    public void setActualManEffort(BigDecimal actualManEffort) {
        this.actualManEffort = actualManEffort;
    }
    public BigDecimal getActualDevEffort() {
        return this.actualDevEffort;
    }
    
    public void setActualDevEffort(BigDecimal actualDevEffort) {
        this.actualDevEffort = actualDevEffort;
    }
    public BigDecimal getCorrectionCost() {
        return this.correctionCost;
    }
    
    public void setCorrectionCost(BigDecimal correctionCost) {
        this.correctionCost = correctionCost;
    }
    public BigDecimal getTransCost() {
        return this.transCost;
    }
    
    public void setTransCost(BigDecimal transCost) {
        this.transCost = transCost;
    }
    public BigDecimal getActualEffort() {
        return this.actualEffort;
    }
    
    public void setActualEffort(BigDecimal actualEffort) {
        this.actualEffort = actualEffort;
    }
    public BigDecimal getTotalReqCommittedSize() {
        return this.totalReqCommittedSize;
    }
    
    public void setTotalReqCommittedSize(BigDecimal totalReqCommittedSize) {
        this.totalReqCommittedSize = totalReqCommittedSize;
    }
    public BigDecimal getTotalReqDesignedSize() {
        return this.totalReqDesignedSize;
    }
    
    public void setTotalReqDesignedSize(BigDecimal totalReqDesignedSize) {
        this.totalReqDesignedSize = totalReqDesignedSize;
    }
    public BigDecimal getTotalReqCoded() {
        return this.totalReqCoded;
    }
    
    public void setTotalReqCoded(BigDecimal totalReqCoded) {
        this.totalReqCoded = totalReqCoded;
    }
    public BigDecimal getRequirementStability() {
        return this.requirementStability;
    }
    
    public void setRequirementStability(BigDecimal requirementStability) {
        this.requirementStability = requirementStability;
    }
    public BigDecimal getTotalReqTestedSize() {
        return this.totalReqTestedSize;
    }
    
    public void setTotalReqTestedSize(BigDecimal totalReqTestedSize) {
        this.totalReqTestedSize = totalReqTestedSize;
    }
    public BigDecimal getTotalRequirementSize() {
        return this.totalRequirementSize;
    }
    
    public void setTotalRequirementSize(BigDecimal totalRequirementSize) {
        this.totalRequirementSize = totalRequirementSize;
    }
    public BigDecimal getTotalReqDeployedSize() {
        return this.totalReqDeployedSize;
    }
    
    public void setTotalReqDeployedSize(BigDecimal totalReqDeployedSize) {
        this.totalReqDeployedSize = totalReqDeployedSize;
    }
    public BigDecimal getAverageReqResponseTime() {
        return this.averageReqResponseTime;
    }
    
    public void setAverageReqResponseTime(BigDecimal averageReqResponseTime) {
        this.averageReqResponseTime = averageReqResponseTime;
    }
    public BigDecimal getTotalAcceptedSize() {
        return this.totalAcceptedSize;
    }
    
    public void setTotalAcceptedSize(BigDecimal totalAcceptedSize) {
        this.totalAcceptedSize = totalAcceptedSize;
    }
    public String getRequirementGraphicsValue() {
        return this.requirementGraphicsValue;
    }
    
    public void setRequirementGraphicsValue(String requirementGraphicsValue) {
        this.requirementGraphicsValue = requirementGraphicsValue;
    }
    public String getRequirementGraphicsName() {
        return this.requirementGraphicsName;
    }
    
    public void setRequirementGraphicsName(String requirementGraphicsName) {
        this.requirementGraphicsName = requirementGraphicsName;
    }




}


