package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;

/**
 * Reportcomments generated by hbm2java
 */
public class Reportcomments  implements java.io.Serializable {


     private BigDecimal reportcommentsId;
     private Project project;
     private String reportType;
     private Date reportDate;
     private Clob comments;

    public Reportcomments() {
    }

	
    public Reportcomments(BigDecimal reportcommentsId, Project project, String reportType, Date reportDate) {
        this.reportcommentsId = reportcommentsId;
        this.project = project;
        this.reportType = reportType;
        this.reportDate = reportDate;
    }
    public Reportcomments(BigDecimal reportcommentsId, Project project, String reportType, Date reportDate, Clob comments) {
       this.reportcommentsId = reportcommentsId;
       this.project = project;
       this.reportType = reportType;
       this.reportDate = reportDate;
       this.comments = comments;
    }
   
    public BigDecimal getReportcommentsId() {
        return this.reportcommentsId;
    }
    
    public void setReportcommentsId(BigDecimal reportcommentsId) {
        this.reportcommentsId = reportcommentsId;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public String getReportType() {
        return this.reportType;
    }
    
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }
    public Date getReportDate() {
        return this.reportDate;
    }
    
    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }
    public Clob getComments() {
        return this.comments;
    }
    
    public void setComments(Clob comments) {
        this.comments = comments;
    }




}


