package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * RiskSourceMitigation generated by hbm2java
 */
public class RiskSourceMitigation  implements java.io.Serializable {


     private BigDecimal riskSourceMitigationId;
     private BigDecimal sourceId;
     private String mitigationTemp;

    public RiskSourceMitigation() {
    }

	
    public RiskSourceMitigation(BigDecimal riskSourceMitigationId) {
        this.riskSourceMitigationId = riskSourceMitigationId;
    }
    public RiskSourceMitigation(BigDecimal riskSourceMitigationId, BigDecimal sourceId, String mitigationTemp) {
       this.riskSourceMitigationId = riskSourceMitigationId;
       this.sourceId = sourceId;
       this.mitigationTemp = mitigationTemp;
    }
   
    public BigDecimal getRiskSourceMitigationId() {
        return this.riskSourceMitigationId;
    }
    
    public void setRiskSourceMitigationId(BigDecimal riskSourceMitigationId) {
        this.riskSourceMitigationId = riskSourceMitigationId;
    }
    public BigDecimal getSourceId() {
        return this.sourceId;
    }
    
    public void setSourceId(BigDecimal sourceId) {
        this.sourceId = sourceId;
    }
    public String getMitigationTemp() {
        return this.mitigationTemp;
    }
    
    public void setMitigationTemp(String mitigationTemp) {
        this.mitigationTemp = mitigationTemp;
    }




}


