package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * WpSizeId generated by hbm2java
 */
public class WpSizeId  implements java.io.Serializable {


     private BigDecimal projectId;
     private BigDecimal wpId;

    public WpSizeId() {
    }

    public WpSizeId(BigDecimal projectId, BigDecimal wpId) {
       this.projectId = projectId;
       this.wpId = wpId;
    }
   
    public BigDecimal getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(BigDecimal projectId) {
        this.projectId = projectId;
    }
    public BigDecimal getWpId() {
        return this.wpId;
    }
    
    public void setWpId(BigDecimal wpId) {
        this.wpId = wpId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WpSizeId) ) return false;
		 WpSizeId castOther = ( WpSizeId ) other; 
         
		 return ( (this.getProjectId()==castOther.getProjectId()) || ( this.getProjectId()!=null && castOther.getProjectId()!=null && this.getProjectId().equals(castOther.getProjectId()) ) )
 && ( (this.getWpId()==castOther.getWpId()) || ( this.getWpId()!=null && castOther.getWpId()!=null && this.getWpId().equals(castOther.getWpId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProjectId() == null ? 0 : this.getProjectId().hashCode() );
         result = 37 * result + ( getWpId() == null ? 0 : this.getWpId().hashCode() );
         return result;
   }   


}


