package openones.oopms.requirement.model;
// Generated Jun 24, 2012 8:23:52 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Requirements  implements java.io.Serializable {

     private String projectName; 
     
     private BigDecimal requirementID;
     private BigDecimal prevProjectID;
     private BigDecimal moduleID;
     private BigDecimal type;
     private BigDecimal reqSize;
     private String srs;
     private String dd;
     private String testcase;
     private String releaseNote;
     private BigDecimal effort;
     private BigDecimal elapsedDay;
     private Date receivedDate;
     private Date responseDate;
     private BigDecimal projectID;
     private Date createDate;
     private Date commmitedDate;
     private Date designedDate;
     private Date codedDate;
     private Date testedDate;     
     private Date deployedDate;
     private Date acceptedDate;
     private Date cancelledDate;
     private String requirement;
     private String codeModule;
     

     
     
    /**
     * Get value of projectName.
     * @return the projectName
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * Set the value for projectName.
     * @param projectName the projectName to set
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public Requirements() {
    }

    public Requirements(BigDecimal requirementID, BigDecimal projectID, String requirement) {
       this.requirementID = requirementID;
       this.projectID = projectID;
       this.requirement = requirement;
    }
        

    /**
     * Get value of requirementID.
     * @return the requirementID
     */
    public BigDecimal getRequirementID() {
        return requirementID;
    }

    /**
     * Set the value for requirementID.
     * @param requirementID the requirementID to set
     */
    public void setRequirementID(BigDecimal requirementID) {
        this.requirementID = requirementID;
    }

    /**
     * Get value of prevProjectID.
     * @return the prevProjectID
     */
    public BigDecimal getPrevProjectID() {
        return prevProjectID;
    }

    /**
     * Set the value for prevProjectID.
     * @param prevProjectID the prevProjectID to set
     */
    public void setPrevProjectID(BigDecimal prevProjectID) {
        this.prevProjectID = prevProjectID;
    }

    /**
     * Get value of moduleID.
     * @return the moduleID
     */
    public BigDecimal getModuleID() {
        return moduleID;
    }

    /**
     * Set the value for moduleID.
     * @param moduleID the moduleID to set
     */
    public void setModuleID(BigDecimal moduleID) {
        this.moduleID = moduleID;
    }

    /**
     * Get value of type.
     * @return the type
     */
    public BigDecimal getType() {
        return type;
    }

    /**
     * Set the value for type.
     * @param type the type to set
     */
    public void setType(BigDecimal type) {
        this.type = type;
    }

    /**
     * Get value of reqSize.
     * @return the reqSize
     */
    public BigDecimal getReqSize() {
        return reqSize;
    }

    /**
     * Set the value for reqSize.
     * @param reqSize the reqSize to set
     */
    public void setReqSize(BigDecimal reqSize) {
        this.reqSize = reqSize;
    }

    /**
     * Get value of srs.
     * @return the srs
     */
    public String getSrs() {
        return srs;
    }

    /**
     * Set the value for srs.
     * @param srs the srs to set
     */
    public void setSrs(String srs) {
        this.srs = srs;
    }

    /**
     * Get value of dd.
     * @return the dd
     */
    public String getDd() {
        return dd;
    }

    /**
     * Set the value for dd.
     * @param dd the dd to set
     */
    public void setDd(String dd) {
        this.dd = dd;
    }

    /**
     * Get value of testcase.
     * @return the testcase
     */
    public String getTestcase() {
        return testcase;
    }

    /**
     * Set the value for testcase.
     * @param testcase the testcase to set
     */
    public void setTestcase(String testcase) {
        this.testcase = testcase;
    }

    /**
     * Get value of releaseNote.
     * @return the releaseNote
     */
    public String getReleaseNote() {
        return releaseNote;
    }

    /**
     * Set the value for releaseNote.
     * @param releaseNote the releaseNote to set
     */
    public void setReleaseNote(String releaseNote) {
        this.releaseNote = releaseNote;
    }

    /**
     * Get value of effort.
     * @return the effort
     */
    public BigDecimal getEffort() {
        return effort;
    }

    /**
     * Set the value for effort.
     * @param effort the effort to set
     */
    public void setEffort(BigDecimal effort) {
        this.effort = effort;
    }

    /**
     * Get value of elapsedDay.
     * @return the elapsedDay
     */
    public BigDecimal getElapsedDay() {
        return elapsedDay;
    }

    /**
     * Set the value for elapsedDay.
     * @param elapsedDay the elapsedDay to set
     */
    public void setElapsedDay(BigDecimal elapsedDay) {
        this.elapsedDay = elapsedDay;
    }

    /**
     * Get value of receivedDate.
     * @return the receivedDate
     */
    public Date getReceivedDate() {
        return receivedDate;
    }

    /**
     * Set the value for receivedDate.
     * @param receivedDate the receivedDate to set
     */
    public void setReceivedDate(Date receivedDate) {
        this.receivedDate = receivedDate;
    }

    /**
     * Get value of responseDate.
     * @return the responseDate
     */
    public Date getResponseDate() {
        return responseDate;
    }

    /**
     * Set the value for responseDate.
     * @param responseDate the responseDate to set
     */
    public void setResponseDate(Date responseDate) {
        this.responseDate = responseDate;
    }

    /**
     * Get value of projectID.
     * @return the projectID
     */
    public BigDecimal getProjectID() {
        return projectID;
    }

    /**
     * Set the value for projectID.
     * @param projectID the projectID to set
     */
    public void setProjectID(BigDecimal projectID) {
        this.projectID = projectID;
    }

    /**
     * Get value of createDate.
     * @return the createDate
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * Set the value for createDate.
     * @param createDate the createDate to set
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * Get value of commmitedDate.
     * @return the commmitedDate
     */
    public Date getCommmitedDate() {
        return commmitedDate;
    }

    /**
     * Set the value for commmitedDate.
     * @param commmitedDate the commmitedDate to set
     */
    public void setCommmitedDate(Date commmitedDate) {
        this.commmitedDate = commmitedDate;
    }

    /**
     * Get value of designedDate.
     * @return the designedDate
     */
    public Date getDesignedDate() {
        return designedDate;
    }

    /**
     * Set the value for designedDate.
     * @param designedDate the designedDate to set
     */
    public void setDesignedDate(Date designedDate) {
        this.designedDate = designedDate;
    }

    /**
     * Get value of codedDate.
     * @return the codedDate
     */
    public Date getCodedDate() {
        return codedDate;
    }

    /**
     * Set the value for codedDate.
     * @param codedDate the codedDate to set
     */
    public void setCodedDate(Date codedDate) {
        this.codedDate = codedDate;
    }

    /**
     * Get value of testedDate.
     * @return the testedDate
     */
    public Date getTestedDate() {
        return testedDate;
    }

    /**
     * Set the value for testedDate.
     * @param testedDate the testedDate to set
     */
    public void setTestedDate(Date testedDate) {
        this.testedDate = testedDate;
    }

    /**
     * Get value of deployedDate.
     * @return the deployedDate
     */
    public Date getDeployedDate() {
        return deployedDate;
    }

    /**
     * Set the value for deployedDate.
     * @param deployedDate the deployedDate to set
     */
    public void setDeployedDate(Date deployedDate) {
        this.deployedDate = deployedDate;
    }

    /**
     * Get value of acceptedDate.
     * @return the acceptedDate
     */
    public Date getAcceptedDate() {
        return acceptedDate;
    }

    /**
     * Set the value for acceptedDate.
     * @param acceptedDate the acceptedDate to set
     */
    public void setAcceptedDate(Date acceptedDate) {
        this.acceptedDate = acceptedDate;
    }

    /**
     * Get value of cancelledDate.
     * @return the cancelledDate
     */
    public Date getCancelledDate() {
        return cancelledDate;
    }

    /**
     * Set the value for cancelledDate.
     * @param cancelledDate the cancelledDate to set
     */
    public void setCancelledDate(Date cancelledDate) {
        this.cancelledDate = cancelledDate;
    }

    /**
     * Get value of requirement.
     * @return the requirement
     */
    public String getRequirement() {
        return requirement;
    }

    /**
     * Set the value for requirement.
     * @param requirement the requirement to set
     */
    public void setRequirement(String requirement) {
        this.requirement = requirement;
    }

    /**
     * Get value of codeModule.
     * @return the codeModule
     */
    public String getCodeModule() {
        return codeModule;
    }

    /**
     * Set the value for codeModule.
     * @param codeModule the codeModule to set
     */
    public void setCodeModule(String codeModule) {
        this.codeModule = codeModule;
    }
      
    

}


