package openones.oopms.projecteye.model;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * ChangesOfProjectPlan generated by hbm2java
 */
public class ChangesOfProjectPlan  implements java.io.Serializable {


     private BigDecimal changeId;
     private String version;
     private Project project;
     private String item;
     private String changes;
     private String reason;
     private String note;
     private Date changeDate;
     private String action;

    public ChangesOfProjectPlan() {
    }

	
    public ChangesOfProjectPlan(BigDecimal changeId) {
        this.changeId = changeId;
    }
    public ChangesOfProjectPlan(BigDecimal changeId, Project project, String item, String changes, String reason, String note, Date changeDate, String action) {
       this.changeId = changeId;
       this.project = project;
       this.item = item;
       this.changes = changes;
       this.reason = reason;
       this.note = note;
       this.changeDate = changeDate;
       this.action = action;
    }
   
    public BigDecimal getChangeId() {
        return this.changeId;
    }
    
    public void setChangeId(BigDecimal changeId) {
        this.changeId = changeId;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public String getChanges() {
        return this.changes;
    }
    
    public void setChanges(String changes) {
        this.changes = changes;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Date getChangeDate() {
        return this.changeDate;
    }
    
    public void setChangeDate(Date changeDate) {
        this.changeDate = changeDate;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }




}


