package openones.oopms.projecteye.model;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Ncconstant generated by hbm2java
 */
public class Ncconstant  implements java.io.Serializable {


     private BigDecimal constantid;
     private String type;
     private String description;
     private BigDecimal systemtype;
     private BigDecimal usage;

    public Ncconstant() {
    }

	
    public Ncconstant(BigDecimal constantid, String type, String description, BigDecimal systemtype) {
        this.constantid = constantid;
        this.type = type;
        this.description = description;
        this.systemtype = systemtype;
    }
    public Ncconstant(BigDecimal constantid, String type, String description, BigDecimal systemtype, BigDecimal usage) {
       this.constantid = constantid;
       this.type = type;
       this.description = description;
       this.systemtype = systemtype;
       this.usage = usage;
    }
   
    public BigDecimal getConstantid() {
        return this.constantid;
    }
    
    public void setConstantid(BigDecimal constantid) {
        this.constantid = constantid;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getSystemtype() {
        return this.systemtype;
    }
    
    public void setSystemtype(BigDecimal systemtype) {
        this.systemtype = systemtype;
    }
    public BigDecimal getUsage() {
        return this.usage;
    }
    
    public void setUsage(BigDecimal usage) {
        this.usage = usage;
    }




}


