package openones.oopms.projecteye.model;
// Generated Aug 9, 2012 10:39:08 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * OopmsCostDailyExpense generated by hbm2java
 */
public class OopmsCostDailyExpense  implements java.io.Serializable {


     private BigDecimal oopmsCostDailyExpenseId;
     private BigDecimal projectId;
     private String name;
     private BigDecimal cost;
     private Date startDate;
     private Date endDate;
     private String dateUsed;
     private BigDecimal type;
     private String description;

    public OopmsCostDailyExpense() {
    }

	
    public OopmsCostDailyExpense(BigDecimal oopmsCostDailyExpenseId, BigDecimal projectId) {
        this.oopmsCostDailyExpenseId = oopmsCostDailyExpenseId;
        this.projectId = projectId;
    }
    public OopmsCostDailyExpense(BigDecimal oopmsCostDailyExpenseId, BigDecimal projectId, String name, BigDecimal cost, Date startDate, Date endDate, String dateUsed, BigDecimal type, String description) {
       this.oopmsCostDailyExpenseId = oopmsCostDailyExpenseId;
       this.projectId = projectId;
       this.name = name;
       this.cost = cost;
       this.startDate = startDate;
       this.endDate = endDate;
       this.dateUsed = dateUsed;
       this.type = type;
       this.description = description;
    }
   
    public BigDecimal getOopmsCostDailyExpenseId() {
        return this.oopmsCostDailyExpenseId;
    }
    
    public void setOopmsCostDailyExpenseId(BigDecimal oopmsCostDailyExpenseId) {
        this.oopmsCostDailyExpenseId = oopmsCostDailyExpenseId;
    }
    public BigDecimal getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(BigDecimal projectId) {
        this.projectId = projectId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getDateUsed() {
        return this.dateUsed;
    }
    
    public void setDateUsed(String dateUsed) {
        this.dateUsed = dateUsed;
    }
    public BigDecimal getType() {
        return this.type;
    }
    
    public void setType(BigDecimal type) {
        this.type = type;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


