DROP TABLE PROJECT_STATUS;
CREATE TABLE PROJECT_STATUS ( PROJECT_STATUS_ID NUMBER NOT NULL, PROJECT_STATUS_NAME VARCHAR2(100) NOT NULL, PRIMARY KEY (PROJECT_STATUS_ID) );
insert into PROJECT_STATUS (PROJECT_STATUS_ID, PROJECT_STATUS_NAME) values (1, 'On-going');
insert into PROJECT_STATUS (PROJECT_STATUS_ID, PROJECT_STATUS_NAME) values (2, 'Completed');
insert into PROJECT_STATUS (PROJECT_STATUS_ID, PROJECT_STATUS_NAME) values (3, 'Cancelled');
insert into PROJECT_STATUS (PROJECT_STATUS_ID, PROJECT_STATUS_NAME) values (4, 'Tentative');
