DROP TABLE TASKS;
CREATE TABLE TASKS ( TASKID NUMBER NOT NULL, WORKUNITID NUMBER, DESCRIPTION VARCHAR2(1000) NOT NULL, ASSIGNEDTO NUMBER NOT NULL, EFFORT NUMBER, PLAN_DATE DATE NOT NULL, ACTUAL_DATE DATE, STATUS NUMBER(1) NOT NULL, TYPE NUMBER(2), NOTE VARCHAR2(200), PROCESS NUMBER NOT NULL, REPLAN_DATE DATE, FEASIBLE NUMBER(1), CODE VARCHAR2(20), TASKNAME NVARCHAR2(100) NOT NULL, STAGEID NUMBER NOT NULL, PRODUCT NUMBER, PRODUCTSIZE NUMBER, COMPLETEDSIZE NUMBER, STARTDATE DATE, PLANNEDEFFORT NUMBER, CURRENTEFFORT NUMBER, PROJECTID NUMBER NOT NULL, STATUSID NUMBER NOT NULL, ACTIVE NUMBER(1), MODULEID NUMBER, SIZEUNIT NUMBER, PRIMARY KEY (TASKID) );
COMMENT ON TABLE TASKS IS 'Tasks (Insight)';
ALTER TABLE TASKS ADD CONSTRAINT FK_TASKS_WU_ID FOREIGN KEY (WORKUNITID) REFERENCES WORKUNIT (WORKUNITID);
ALTER TABLE TASKS ADD CONSTRAINT FK_TASKS_MODULE_ID FOREIGN KEY (MODULEID) REFERENCES MODULE (MODULE_ID);
