-- Upgrade table of FMS database
ALTER TABLE TASKS ADD  (
        TASKNAME NVARCHAR2(100) NOT NULL,
        STAGEID NUMBER NOT NULL,
        PRODUCT NUMBER,
        PRODUCTSIZE NUMBER,
        COMPLETEDSIZE NUMBER,
        STARTDATE DATE,
        PLANNEDEFFORT NUMBER,
        CURRENTEFFORT NUMBER,
        PROJECTID NUMBER NOT NULL,
        STATUSID NUMBER NOT NULL,
        ACTIVE NUMBER(1)
)
/
ALTER TABLE TASKS ADD  (
        CONSTRAINT TASKS_PK PRIMARY KEY (TASKID)
)
/
-- Project status content kinds of status of task
DROP TABLE PROJECT_STATUS;
CREATE TABLE PROJECT_STATUS ( PROJECT_STATUS_ID NUMBER NOT NULL, PROJECT_STATUS_NAME VARCHAR2(100) NOT NULL, PRIMARY KEY (PROJECT_STATUS_ID) );
insert into PROJECT_STATUS (PROJECT_STATUS_ID, PROJECT_STATUS_NAME) values (1, 'On-going');
insert into PROJECT_STATUS (PROJECT_STATUS_ID, PROJECT_STATUS_NAME) values (2, 'Completed');
insert into PROJECT_STATUS (PROJECT_STATUS_ID, PROJECT_STATUS_NAME) values (3, 'Cancelled');
insert into PROJECT_STATUS (PROJECT_STATUS_ID, PROJECT_STATUS_NAME) values (4, 'Tentative');