-- Upgrade table of FMS database
ALTER TABLE TASKS ADD  (
        TASKNAME NVARCHAR2(100) NOT NULL,
        STAGEID NUMBER NOT NULL,
        PRODUCT NUMBER,
        PRODUCTSIZE NUMBER,
        COMPLETEDSIZE NUMBER,
        STARTDATE DATE,
        PLANNEDEFFORT NUMBER,
        CURRENTEFFORT NUMBER,
        PROJECTID NUMBER NOT NULL,
        STATUSID NUMBER NOT NULL,
        ACTIVE NUMBER(1)
)
/
ALTER TABLE TASKS ADD  (
        CONSTRAINT TASKS_PK PRIMARY KEY (TASKID)
)
/