package openones.oopms.projecteye.model;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Issue generated by hbm2java
 */
public class Issue  implements java.io.Serializable {


     private long issueid;
     private Workunit workunit;
     private String description;
     private int statusid;
     private int priorityid;
     private int typeid;
     private String owner;
     private Date startdate;
     private Date duedate;
     private String comments;
     private Date closeddate;
     private String reference;
     private String creator;
     private BigDecimal riskid;
     private Short processId;
     private BigDecimal wuId;

    public Issue() {
    }

	
    public Issue(long issueid, Workunit workunit, String description, int statusid, int priorityid, int typeid) {
        this.issueid = issueid;
        this.workunit = workunit;
        this.description = description;
        this.statusid = statusid;
        this.priorityid = priorityid;
        this.typeid = typeid;
    }
    public Issue(long issueid, Workunit workunit, String description, int statusid, int priorityid, int typeid, String owner, Date startdate, Date duedate, String comments, Date closeddate, String reference, String creator, BigDecimal riskid, Short processId, BigDecimal wuId) {
       this.issueid = issueid;
       this.workunit = workunit;
       this.description = description;
       this.statusid = statusid;
       this.priorityid = priorityid;
       this.typeid = typeid;
       this.owner = owner;
       this.startdate = startdate;
       this.duedate = duedate;
       this.comments = comments;
       this.closeddate = closeddate;
       this.reference = reference;
       this.creator = creator;
       this.riskid = riskid;
       this.processId = processId;
       this.wuId = wuId;
    }
   
    public long getIssueid() {
        return this.issueid;
    }
    
    public void setIssueid(long issueid) {
        this.issueid = issueid;
    }
    public Workunit getWorkunit() {
        return this.workunit;
    }
    
    public void setWorkunit(Workunit workunit) {
        this.workunit = workunit;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getStatusid() {
        return this.statusid;
    }
    
    public void setStatusid(int statusid) {
        this.statusid = statusid;
    }
    public int getPriorityid() {
        return this.priorityid;
    }
    
    public void setPriorityid(int priorityid) {
        this.priorityid = priorityid;
    }
    public int getTypeid() {
        return this.typeid;
    }
    
    public void setTypeid(int typeid) {
        this.typeid = typeid;
    }
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getDuedate() {
        return this.duedate;
    }
    
    public void setDuedate(Date duedate) {
        this.duedate = duedate;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public Date getCloseddate() {
        return this.closeddate;
    }
    
    public void setCloseddate(Date closeddate) {
        this.closeddate = closeddate;
    }
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public BigDecimal getRiskid() {
        return this.riskid;
    }
    
    public void setRiskid(BigDecimal riskid) {
        this.riskid = riskid;
    }
    public Short getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(Short processId) {
        this.processId = processId;
    }
    public BigDecimal getWuId() {
        return this.wuId;
    }
    
    public void setWuId(BigDecimal wuId) {
        this.wuId = wuId;
    }




}


