package openones.oopms.projecteye.model;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Milestone generated by hbm2java
 */
public class Milestone  implements java.io.Serializable {


     private BigDecimal milestoneId;
     private Project project;
     private Developer developer;
     private String name;
     private BigDecimal complete;
     private Date baseStartDate;
     private Date planStartDate;
     private Date actualStartDate;
     private Date baseFinishDate;
     private Date planFinishDate;
     private Date actualFinishDate;
     private BigDecimal baseEffort;
     private BigDecimal planEffort;
     private BigDecimal actualEffort;
     private String description;
     private BigDecimal stageId;
     private String milestone;
     private Clob comments;
     private BigDecimal standardstage;
     private BigDecimal projectsize;
     private BigDecimal effefectiveness;
     private BigDecimal customersatisfaction;
     private BigDecimal acceptanceofdeliverables;
     private BigDecimal requirementcompleteness;
     private BigDecimal timeliness;
     private BigDecimal leakage;
     private BigDecimal correctioncost;
     private BigDecimal processcompliance;
     private BigDecimal workorder;
     private BigDecimal acceptancenote;
     private BigDecimal projectplan;
     private BigDecimal projectreports;
     private BigDecimal prestige;
     private BigDecimal projectpoint;
     private String projecteval;
     private BigDecimal cuspoint;
     private BigDecimal effortefficiency;
     private BigDecimal overduencsobs;
     private Set cusPoints = new HashSet(0);
     private Set plansQcStages = new HashSet(0);
     private Set iterations = new HashSet(0);

    public Milestone() {
    }

	
    public Milestone(BigDecimal milestoneId, Project project, String name, BigDecimal complete) {
        this.milestoneId = milestoneId;
        this.project = project;
        this.name = name;
        this.complete = complete;
    }
    public Milestone(BigDecimal milestoneId, Project project, Developer developer, String name, BigDecimal complete, Date baseStartDate, Date planStartDate, Date actualStartDate, Date baseFinishDate, Date planFinishDate, Date actualFinishDate, BigDecimal baseEffort, BigDecimal planEffort, BigDecimal actualEffort, String description, BigDecimal stageId, String milestone, Clob comments, BigDecimal standardstage, BigDecimal projectsize, BigDecimal effefectiveness, BigDecimal customersatisfaction, BigDecimal acceptanceofdeliverables, BigDecimal requirementcompleteness, BigDecimal timeliness, BigDecimal leakage, BigDecimal correctioncost, BigDecimal processcompliance, BigDecimal workorder, BigDecimal acceptancenote, BigDecimal projectplan, BigDecimal projectreports, BigDecimal prestige, BigDecimal projectpoint, String projecteval, BigDecimal cuspoint, BigDecimal effortefficiency, BigDecimal overduencsobs, Set cusPoints, Set plansQcStages, Set iterations) {
       this.milestoneId = milestoneId;
       this.project = project;
       this.developer = developer;
       this.name = name;
       this.complete = complete;
       this.baseStartDate = baseStartDate;
       this.planStartDate = planStartDate;
       this.actualStartDate = actualStartDate;
       this.baseFinishDate = baseFinishDate;
       this.planFinishDate = planFinishDate;
       this.actualFinishDate = actualFinishDate;
       this.baseEffort = baseEffort;
       this.planEffort = planEffort;
       this.actualEffort = actualEffort;
       this.description = description;
       this.stageId = stageId;
       this.milestone = milestone;
       this.comments = comments;
       this.standardstage = standardstage;
       this.projectsize = projectsize;
       this.effefectiveness = effefectiveness;
       this.customersatisfaction = customersatisfaction;
       this.acceptanceofdeliverables = acceptanceofdeliverables;
       this.requirementcompleteness = requirementcompleteness;
       this.timeliness = timeliness;
       this.leakage = leakage;
       this.correctioncost = correctioncost;
       this.processcompliance = processcompliance;
       this.workorder = workorder;
       this.acceptancenote = acceptancenote;
       this.projectplan = projectplan;
       this.projectreports = projectreports;
       this.prestige = prestige;
       this.projectpoint = projectpoint;
       this.projecteval = projecteval;
       this.cuspoint = cuspoint;
       this.effortefficiency = effortefficiency;
       this.overduencsobs = overduencsobs;
       this.cusPoints = cusPoints;
       this.plansQcStages = plansQcStages;
       this.iterations = iterations;
    }
   
    public BigDecimal getMilestoneId() {
        return this.milestoneId;
    }
    
    public void setMilestoneId(BigDecimal milestoneId) {
        this.milestoneId = milestoneId;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public Developer getDeveloper() {
        return this.developer;
    }
    
    public void setDeveloper(Developer developer) {
        this.developer = developer;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getComplete() {
        return this.complete;
    }
    
    public void setComplete(BigDecimal complete) {
        this.complete = complete;
    }
    public Date getBaseStartDate() {
        return this.baseStartDate;
    }
    
    public void setBaseStartDate(Date baseStartDate) {
        this.baseStartDate = baseStartDate;
    }
    public Date getPlanStartDate() {
        return this.planStartDate;
    }
    
    public void setPlanStartDate(Date planStartDate) {
        this.planStartDate = planStartDate;
    }
    public Date getActualStartDate() {
        return this.actualStartDate;
    }
    
    public void setActualStartDate(Date actualStartDate) {
        this.actualStartDate = actualStartDate;
    }
    public Date getBaseFinishDate() {
        return this.baseFinishDate;
    }
    
    public void setBaseFinishDate(Date baseFinishDate) {
        this.baseFinishDate = baseFinishDate;
    }
    public Date getPlanFinishDate() {
        return this.planFinishDate;
    }
    
    public void setPlanFinishDate(Date planFinishDate) {
        this.planFinishDate = planFinishDate;
    }
    public Date getActualFinishDate() {
        return this.actualFinishDate;
    }
    
    public void setActualFinishDate(Date actualFinishDate) {
        this.actualFinishDate = actualFinishDate;
    }
    public BigDecimal getBaseEffort() {
        return this.baseEffort;
    }
    
    public void setBaseEffort(BigDecimal baseEffort) {
        this.baseEffort = baseEffort;
    }
    public BigDecimal getPlanEffort() {
        return this.planEffort;
    }
    
    public void setPlanEffort(BigDecimal planEffort) {
        this.planEffort = planEffort;
    }
    public BigDecimal getActualEffort() {
        return this.actualEffort;
    }
    
    public void setActualEffort(BigDecimal actualEffort) {
        this.actualEffort = actualEffort;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getStageId() {
        return this.stageId;
    }
    
    public void setStageId(BigDecimal stageId) {
        this.stageId = stageId;
    }
    public String getMilestone() {
        return this.milestone;
    }
    
    public void setMilestone(String milestone) {
        this.milestone = milestone;
    }
    public Clob getComments() {
        return this.comments;
    }
    
    public void setComments(Clob comments) {
        this.comments = comments;
    }
    public BigDecimal getStandardstage() {
        return this.standardstage;
    }
    
    public void setStandardstage(BigDecimal standardstage) {
        this.standardstage = standardstage;
    }
    public BigDecimal getProjectsize() {
        return this.projectsize;
    }
    
    public void setProjectsize(BigDecimal projectsize) {
        this.projectsize = projectsize;
    }
    public BigDecimal getEffefectiveness() {
        return this.effefectiveness;
    }
    
    public void setEffefectiveness(BigDecimal effefectiveness) {
        this.effefectiveness = effefectiveness;
    }
    public BigDecimal getCustomersatisfaction() {
        return this.customersatisfaction;
    }
    
    public void setCustomersatisfaction(BigDecimal customersatisfaction) {
        this.customersatisfaction = customersatisfaction;
    }
    public BigDecimal getAcceptanceofdeliverables() {
        return this.acceptanceofdeliverables;
    }
    
    public void setAcceptanceofdeliverables(BigDecimal acceptanceofdeliverables) {
        this.acceptanceofdeliverables = acceptanceofdeliverables;
    }
    public BigDecimal getRequirementcompleteness() {
        return this.requirementcompleteness;
    }
    
    public void setRequirementcompleteness(BigDecimal requirementcompleteness) {
        this.requirementcompleteness = requirementcompleteness;
    }
    public BigDecimal getTimeliness() {
        return this.timeliness;
    }
    
    public void setTimeliness(BigDecimal timeliness) {
        this.timeliness = timeliness;
    }
    public BigDecimal getLeakage() {
        return this.leakage;
    }
    
    public void setLeakage(BigDecimal leakage) {
        this.leakage = leakage;
    }
    public BigDecimal getCorrectioncost() {
        return this.correctioncost;
    }
    
    public void setCorrectioncost(BigDecimal correctioncost) {
        this.correctioncost = correctioncost;
    }
    public BigDecimal getProcesscompliance() {
        return this.processcompliance;
    }
    
    public void setProcesscompliance(BigDecimal processcompliance) {
        this.processcompliance = processcompliance;
    }
    public BigDecimal getWorkorder() {
        return this.workorder;
    }
    
    public void setWorkorder(BigDecimal workorder) {
        this.workorder = workorder;
    }
    public BigDecimal getAcceptancenote() {
        return this.acceptancenote;
    }
    
    public void setAcceptancenote(BigDecimal acceptancenote) {
        this.acceptancenote = acceptancenote;
    }
    public BigDecimal getProjectplan() {
        return this.projectplan;
    }
    
    public void setProjectplan(BigDecimal projectplan) {
        this.projectplan = projectplan;
    }
    public BigDecimal getProjectreports() {
        return this.projectreports;
    }
    
    public void setProjectreports(BigDecimal projectreports) {
        this.projectreports = projectreports;
    }
    public BigDecimal getPrestige() {
        return this.prestige;
    }
    
    public void setPrestige(BigDecimal prestige) {
        this.prestige = prestige;
    }
    public BigDecimal getProjectpoint() {
        return this.projectpoint;
    }
    
    public void setProjectpoint(BigDecimal projectpoint) {
        this.projectpoint = projectpoint;
    }
    public String getProjecteval() {
        return this.projecteval;
    }
    
    public void setProjecteval(String projecteval) {
        this.projecteval = projecteval;
    }
    public BigDecimal getCuspoint() {
        return this.cuspoint;
    }
    
    public void setCuspoint(BigDecimal cuspoint) {
        this.cuspoint = cuspoint;
    }
    public BigDecimal getEffortefficiency() {
        return this.effortefficiency;
    }
    
    public void setEffortefficiency(BigDecimal effortefficiency) {
        this.effortefficiency = effortefficiency;
    }
    public BigDecimal getOverduencsobs() {
        return this.overduencsobs;
    }
    
    public void setOverduencsobs(BigDecimal overduencsobs) {
        this.overduencsobs = overduencsobs;
    }
    public Set getCusPoints() {
        return this.cusPoints;
    }
    
    public void setCusPoints(Set cusPoints) {
        this.cusPoints = cusPoints;
    }
    public Set getPlansQcStages() {
        return this.plansQcStages;
    }
    
    public void setPlansQcStages(Set plansQcStages) {
        this.plansQcStages = plansQcStages;
    }
    public Set getIterations() {
        return this.iterations;
    }
    
    public void setIterations(Set iterations) {
        this.iterations = iterations;
    }




}


