package openones.oopms.projecteye.model;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Stage generated by hbm2java
 */
public class Stage  implements java.io.Serializable {


     private BigDecimal stageId;
     private String name;

    public Stage() {
    }

    public Stage(BigDecimal stageId, String name) {
       this.stageId = stageId;
       this.name = name;
    }
   
    public BigDecimal getStageId() {
        return this.stageId;
    }
    
    public void setStageId(BigDecimal stageId) {
        this.stageId = stageId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


