package openones.oopms.requirement.model;
// Generated Jul 14, 2012 1:31:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Assignment generated by hbm2java
 */
public class Assignment  implements java.io.Serializable {


     private BigDecimal assignmentId;     
     private Developer developer;     
     private Project project;
     private byte type;
     private Date beginDate;
     private Date endDate;
     private BigDecimal usage;
     private Short response;
     private String note;
     private String qualification;

    public Assignment() {
    }

	
    public Assignment(BigDecimal assignmentId, Developer developer, Project project, byte type) {
        this.assignmentId = assignmentId;
        this.developer = developer;
        this.project = project;
        this.type = type;
    }
    public Assignment(BigDecimal assignmentId, Developer developer, Project project, byte type, Date beginDate, Date endDate, BigDecimal usage, Short response, String note, String qualification) {
       this.assignmentId = assignmentId;       
       this.developer = developer;       
       this.project = project;
       this.type = type;
       this.beginDate = beginDate;
       this.endDate = endDate;
       this.usage = usage;
       this.response = response;
       this.note = note;
       this.qualification = qualification;
    }
   
    public BigDecimal getAssignmentId() {
        return this.assignmentId;
    }
    
    public void setAssignmentId(BigDecimal assignmentId) {
        this.assignmentId = assignmentId;
    }
    
    public Developer getDeveloper() {
        return this.developer;
    }
    
    public void setDeveloper(Developer developer) {
        this.developer = developer;
    }
   
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public BigDecimal getUsage() {
        return this.usage;
    }
    
    public void setUsage(BigDecimal usage) {
        this.usage = usage;
    }
    public Short getResponse() {
        return this.response;
    }
    
    public void setResponse(Short response) {
        this.response = response;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }




}


