package openones.oopms.requirement.model;
// Generated Jul 6, 2012 7:55:26 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Timesheet generated by hbm2java
 */
public class Timesheet  implements java.io.Serializable {


     private BigDecimal timesheetId;
     private Project project;
     private String processName;
     private String towName;
     private String workProductName;
     private BigDecimal developerId;
     private Date createDate;
     private Date occurDate;
     private String occurDateString;
     private String durationString;
     private BigDecimal duration;
     private BigDecimal status;
     private BigDecimal kpaId;
     private BigDecimal towId;
     private BigDecimal processId;
     private BigDecimal wpId;
     private String approvedByLeader;
     private String approvedBySepg;
     private String description;
     private String rcomment;
     private Date plapprovedtime;
     private Date qaapprovedtime;
     private BigDecimal newTimesheetId;
     private String dummyField;
     private String projectName;
    public Timesheet() {
    }

    
    

    public String getDurationString() {
        return durationString;
    }




    public void setDurationString(String durationString) {
        this.durationString = durationString;
    }




    public String getOccurDateString() {
        return occurDateString;
    }




    public void setOccurDateString(String occurDateString) {
        this.occurDateString = occurDateString;
    }




    public String getTowName() {
        return towName;
    }

    public void setTowName(String towName) {
        this.towName = towName;
    }



    public String getWorkProductName() {
        return workProductName;
    }



    public void setWorkProductName(String workProductName) {
        this.workProductName = workProductName;
    }



    public String getProcessName() {
        return processName;
    }



    public void setProcessName(String processName) {
        this.processName = processName;
    }



    public String getProjectName() {
        return projectName;
    }


    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }


    public Timesheet(BigDecimal timesheetId, Project project, BigDecimal developerId, Date createDate, Date occurDate, BigDecimal duration) {
        this.timesheetId = timesheetId;
        this.project = project;
        this.developerId = developerId;
        this.createDate = createDate;
        this.occurDate = occurDate;
        this.duration = duration;
    }
    public Timesheet(BigDecimal timesheetId, Project project, BigDecimal developerId, Date createDate, Date occurDate, BigDecimal duration, BigDecimal status, BigDecimal kpaId, BigDecimal towId, BigDecimal processId, BigDecimal wpId, String approvedByLeader, String approvedBySepg, String description, String rcomment, Date plapprovedtime, Date qaapprovedtime, BigDecimal newTimesheetId, String dummyField) {
       this.timesheetId = timesheetId;
       this.project = project;
       this.developerId = developerId;
       this.createDate = createDate;
       this.occurDate = occurDate;
       this.duration = duration;
       this.status = status;
       this.kpaId = kpaId;
       this.towId = towId;
       this.processId = processId;
       this.wpId = wpId;
       this.approvedByLeader = approvedByLeader;
       this.approvedBySepg = approvedBySepg;
       this.description = description;
       this.rcomment = rcomment;
       this.plapprovedtime = plapprovedtime;
       this.qaapprovedtime = qaapprovedtime;
       this.newTimesheetId = newTimesheetId;
       this.dummyField = dummyField;
    }
   
    public BigDecimal getTimesheetId() {
        return this.timesheetId;
    }
    
    public void setTimesheetId(BigDecimal timesheetId) {
        this.timesheetId = timesheetId;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public BigDecimal getDeveloperId() {
        return this.developerId;
    }
    
    public void setDeveloperId(BigDecimal developerId) {
        this.developerId = developerId;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getOccurDate() {
        return this.occurDate;
    }
    
    public void setOccurDate(Date occurDate) {
        this.occurDate = occurDate;
    }
    public BigDecimal getDuration() {
        return this.duration;
    }
    
    public void setDuration(BigDecimal duration) {
        this.duration = duration;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public BigDecimal getKpaId() {
        return this.kpaId;
    }
    
    public void setKpaId(BigDecimal kpaId) {
        this.kpaId = kpaId;
    }
    public BigDecimal getTowId() {
        return this.towId;
    }
    
    public void setTowId(BigDecimal towId) {
        this.towId = towId;
    }
    public BigDecimal getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(BigDecimal processId) {
        this.processId = processId;
    }
    public BigDecimal getWpId() {
        return this.wpId;
    }
    
    public void setWpId(BigDecimal wpId) {
        this.wpId = wpId;
    }
    public String getApprovedByLeader() {
        return this.approvedByLeader;
    }
    
    public void setApprovedByLeader(String approvedByLeader) {
        this.approvedByLeader = approvedByLeader;
    }
    public String getApprovedBySepg() {
        return this.approvedBySepg;
    }
    
    public void setApprovedBySepg(String approvedBySepg) {
        this.approvedBySepg = approvedBySepg;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getRcomment() {
        return this.rcomment;
    }
    
    public void setRcomment(String rcomment) {
        this.rcomment = rcomment;
    }
    public Date getPlapprovedtime() {
        return this.plapprovedtime;
    }
    
    public void setPlapprovedtime(Date plapprovedtime) {
        this.plapprovedtime = plapprovedtime;
    }
    public Date getQaapprovedtime() {
        return this.qaapprovedtime;
    }
    
    public void setQaapprovedtime(Date qaapprovedtime) {
        this.qaapprovedtime = qaapprovedtime;
    }
    public BigDecimal getNewTimesheetId() {
        return this.newTimesheetId;
    }
    
    public void setNewTimesheetId(BigDecimal newTimesheetId) {
        this.newTimesheetId = newTimesheetId;
    }
    public String getDummyField() {
        return this.dummyField;
    }
    
    public void setDummyField(String dummyField) {
        this.dummyField = dummyField;
    }




}


