package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * DefectHistory generated by hbm2java
 */
public class DefectHistory  implements java.io.Serializable {


     private BigDecimal defectId;
     private String history;

    public DefectHistory() {
    }

	
    public DefectHistory(BigDecimal defectId) {
        this.defectId = defectId;
    }
    public DefectHistory(BigDecimal defectId, String history) {
       this.defectId = defectId;
       this.history = history;
    }
   
    public BigDecimal getDefectId() {
        return this.defectId;
    }
    
    public void setDefectId(BigDecimal defectId) {
        this.defectId = defectId;
    }
    public String getHistory() {
        return this.history;
    }
    
    public void setHistory(String history) {
        this.history = history;
    }




}


