package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * DefectQuery generated by hbm2java
 */
public class DefectQuery  implements java.io.Serializable {


     private BigDecimal queryId;
     private Developer developer;
     private Project project;
     private String title;
     private String scope;
     private String sqlText;

    public DefectQuery() {
    }

	
    public DefectQuery(BigDecimal queryId, Developer developer, Project project, String title, String scope) {
        this.queryId = queryId;
        this.developer = developer;
        this.project = project;
        this.title = title;
        this.scope = scope;
    }
    public DefectQuery(BigDecimal queryId, Developer developer, Project project, String title, String scope, String sqlText) {
       this.queryId = queryId;
       this.developer = developer;
       this.project = project;
       this.title = title;
       this.scope = scope;
       this.sqlText = sqlText;
    }
   
    public BigDecimal getQueryId() {
        return this.queryId;
    }
    
    public void setQueryId(BigDecimal queryId) {
        this.queryId = queryId;
    }
    public Developer getDeveloper() {
        return this.developer;
    }
    
    public void setDeveloper(Developer developer) {
        this.developer = developer;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getScope() {
        return this.scope;
    }
    
    public void setScope(String scope) {
        this.scope = scope;
    }
    public String getSqlText() {
        return this.sqlText;
    }
    
    public void setSqlText(String sqlText) {
        this.sqlText = sqlText;
    }




}


