package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * LanguageCode generated by hbm2java
 */
public class LanguageCode  implements java.io.Serializable {


     private String langCode;
     private String description;
     private Set generalReferences = new HashSet(0);
     private Set referenceDatas = new HashSet(0);

    public LanguageCode() {
    }

	
    public LanguageCode(String langCode) {
        this.langCode = langCode;
    }
    public LanguageCode(String langCode, String description, Set generalReferences, Set referenceDatas) {
       this.langCode = langCode;
       this.description = description;
       this.generalReferences = generalReferences;
       this.referenceDatas = referenceDatas;
    }
   
    public String getLangCode() {
        return this.langCode;
    }
    
    public void setLangCode(String langCode) {
        this.langCode = langCode;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getGeneralReferences() {
        return this.generalReferences;
    }
    
    public void setGeneralReferences(Set generalReferences) {
        this.generalReferences = generalReferences;
    }
    public Set getReferenceDatas() {
        return this.referenceDatas;
    }
    
    public void setReferenceDatas(Set referenceDatas) {
        this.referenceDatas = referenceDatas;
    }




}


