package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ProjectCost generated by hbm2java
 */
public class ProjectCost  implements java.io.Serializable {


     private BigDecimal projectCostId;
     private BigDecimal projectPlanId;
     private String activities;
     private Long type;
     private BigDecimal effort;
     private BigDecimal cost;

    public ProjectCost() {
    }

	
    public ProjectCost(BigDecimal projectCostId) {
        this.projectCostId = projectCostId;
    }
    public ProjectCost(BigDecimal projectCostId, BigDecimal projectPlanId, String activities, Long type, BigDecimal effort, BigDecimal cost) {
       this.projectCostId = projectCostId;
       this.projectPlanId = projectPlanId;
       this.activities = activities;
       this.type = type;
       this.effort = effort;
       this.cost = cost;
    }
   
    public BigDecimal getProjectCostId() {
        return this.projectCostId;
    }
    
    public void setProjectCostId(BigDecimal projectCostId) {
        this.projectCostId = projectCostId;
    }
    public BigDecimal getProjectPlanId() {
        return this.projectPlanId;
    }
    
    public void setProjectPlanId(BigDecimal projectPlanId) {
        this.projectPlanId = projectPlanId;
    }
    public String getActivities() {
        return this.activities;
    }
    
    public void setActivities(String activities) {
        this.activities = activities;
    }
    public Long getType() {
        return this.type;
    }
    
    public void setType(Long type) {
        this.type = type;
    }
    public BigDecimal getEffort() {
        return this.effort;
    }
    
    public void setEffort(BigDecimal effort) {
        this.effort = effort;
    }
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }




}


