package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * QoStrategyForMeeting generated by hbm2java
 */
public class QoStrategyForMeeting  implements java.io.Serializable {


     private BigDecimal qoStratId;
     private BigDecimal qoStratPrjId;
     private String qoStratDesc;
     private String qoStratExpectedBenefits;

    public QoStrategyForMeeting() {
    }

    public QoStrategyForMeeting(BigDecimal qoStratId, BigDecimal qoStratPrjId, String qoStratDesc, String qoStratExpectedBenefits) {
       this.qoStratId = qoStratId;
       this.qoStratPrjId = qoStratPrjId;
       this.qoStratDesc = qoStratDesc;
       this.qoStratExpectedBenefits = qoStratExpectedBenefits;
    }
   
    public BigDecimal getQoStratId() {
        return this.qoStratId;
    }
    
    public void setQoStratId(BigDecimal qoStratId) {
        this.qoStratId = qoStratId;
    }
    public BigDecimal getQoStratPrjId() {
        return this.qoStratPrjId;
    }
    
    public void setQoStratPrjId(BigDecimal qoStratPrjId) {
        this.qoStratPrjId = qoStratPrjId;
    }
    public String getQoStratDesc() {
        return this.qoStratDesc;
    }
    
    public void setQoStratDesc(String qoStratDesc) {
        this.qoStratDesc = qoStratDesc;
    }
    public String getQoStratExpectedBenefits() {
        return this.qoStratExpectedBenefits;
    }
    
    public void setQoStratExpectedBenefits(String qoStratExpectedBenefits) {
        this.qoStratExpectedBenefits = qoStratExpectedBenefits;
    }




}


