package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * RiskContigency generated by hbm2java
 */
public class RiskContigency  implements java.io.Serializable {


     private BigDecimal riskContigencyId;
     private Risk risk;
     private String contigency;
     private String developerAcc;
     private Date planEndDate;
     private Date actualEndDate;
     private BigDecimal actionStatus;

    public RiskContigency() {
    }

	
    public RiskContigency(BigDecimal riskContigencyId) {
        this.riskContigencyId = riskContigencyId;
    }
    public RiskContigency(BigDecimal riskContigencyId, Risk risk, String contigency, String developerAcc, Date planEndDate, Date actualEndDate, BigDecimal actionStatus) {
       this.riskContigencyId = riskContigencyId;
       this.risk = risk;
       this.contigency = contigency;
       this.developerAcc = developerAcc;
       this.planEndDate = planEndDate;
       this.actualEndDate = actualEndDate;
       this.actionStatus = actionStatus;
    }
   
    public BigDecimal getRiskContigencyId() {
        return this.riskContigencyId;
    }
    
    public void setRiskContigencyId(BigDecimal riskContigencyId) {
        this.riskContigencyId = riskContigencyId;
    }
    public Risk getRisk() {
        return this.risk;
    }
    
    public void setRisk(Risk risk) {
        this.risk = risk;
    }
    public String getContigency() {
        return this.contigency;
    }
    
    public void setContigency(String contigency) {
        this.contigency = contigency;
    }
    public String getDeveloperAcc() {
        return this.developerAcc;
    }
    
    public void setDeveloperAcc(String developerAcc) {
        this.developerAcc = developerAcc;
    }
    public Date getPlanEndDate() {
        return this.planEndDate;
    }
    
    public void setPlanEndDate(Date planEndDate) {
        this.planEndDate = planEndDate;
    }
    public Date getActualEndDate() {
        return this.actualEndDate;
    }
    
    public void setActualEndDate(Date actualEndDate) {
        this.actualEndDate = actualEndDate;
    }
    public BigDecimal getActionStatus() {
        return this.actionStatus;
    }
    
    public void setActionStatus(BigDecimal actionStatus) {
        this.actionStatus = actionStatus;
    }




}


