package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TestStrategy generated by hbm2java
 */
public class TestStrategy  implements java.io.Serializable {


     private BigDecimal testId;
     private BigDecimal testPrjId;
     private String testItem;
     private BigDecimal testType;
     private String testReviewer;
     private String testEntryCriteria;
     private String testCompletionCriteria;

    public TestStrategy() {
    }

    public TestStrategy(BigDecimal testId, BigDecimal testPrjId, String testItem, BigDecimal testType, String testReviewer, String testEntryCriteria, String testCompletionCriteria) {
       this.testId = testId;
       this.testPrjId = testPrjId;
       this.testItem = testItem;
       this.testType = testType;
       this.testReviewer = testReviewer;
       this.testEntryCriteria = testEntryCriteria;
       this.testCompletionCriteria = testCompletionCriteria;
    }
   
    public BigDecimal getTestId() {
        return this.testId;
    }
    
    public void setTestId(BigDecimal testId) {
        this.testId = testId;
    }
    public BigDecimal getTestPrjId() {
        return this.testPrjId;
    }
    
    public void setTestPrjId(BigDecimal testPrjId) {
        this.testPrjId = testPrjId;
    }
    public String getTestItem() {
        return this.testItem;
    }
    
    public void setTestItem(String testItem) {
        this.testItem = testItem;
    }
    public BigDecimal getTestType() {
        return this.testType;
    }
    
    public void setTestType(BigDecimal testType) {
        this.testType = testType;
    }
    public String getTestReviewer() {
        return this.testReviewer;
    }
    
    public void setTestReviewer(String testReviewer) {
        this.testReviewer = testReviewer;
    }
    public String getTestEntryCriteria() {
        return this.testEntryCriteria;
    }
    
    public void setTestEntryCriteria(String testEntryCriteria) {
        this.testEntryCriteria = testEntryCriteria;
    }
    public String getTestCompletionCriteria() {
        return this.testCompletionCriteria;
    }
    
    public void setTestCompletionCriteria(String testCompletionCriteria) {
        this.testCompletionCriteria = testCompletionCriteria;
    }




}


