package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * TimesheetExemption generated by hbm2java
 */
public class TimesheetExemption  implements java.io.Serializable {


     private BigDecimal exemptionId;
     private Developer developer;
     private byte type;
     private String weekday;
     private Date fromDate;
     private Date toDate;
     private String reason;
     private String note;
     private String dummyField;
     private BigDecimal newExemptionId;

    public TimesheetExemption() {
    }

	
    public TimesheetExemption(BigDecimal exemptionId, Developer developer, byte type) {
        this.exemptionId = exemptionId;
        this.developer = developer;
        this.type = type;
    }
    public TimesheetExemption(BigDecimal exemptionId, Developer developer, byte type, String weekday, Date fromDate, Date toDate, String reason, String note, String dummyField, BigDecimal newExemptionId) {
       this.exemptionId = exemptionId;
       this.developer = developer;
       this.type = type;
       this.weekday = weekday;
       this.fromDate = fromDate;
       this.toDate = toDate;
       this.reason = reason;
       this.note = note;
       this.dummyField = dummyField;
       this.newExemptionId = newExemptionId;
    }
   
    public BigDecimal getExemptionId() {
        return this.exemptionId;
    }
    
    public void setExemptionId(BigDecimal exemptionId) {
        this.exemptionId = exemptionId;
    }
    public Developer getDeveloper() {
        return this.developer;
    }
    
    public void setDeveloper(Developer developer) {
        this.developer = developer;
    }
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }
    public String getWeekday() {
        return this.weekday;
    }
    
    public void setWeekday(String weekday) {
        this.weekday = weekday;
    }
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getDummyField() {
        return this.dummyField;
    }
    
    public void setDummyField(String dummyField) {
        this.dummyField = dummyField;
    }
    public BigDecimal getNewExemptionId() {
        return this.newExemptionId;
    }
    
    public void setNewExemptionId(BigDecimal newExemptionId) {
        this.newExemptionId = newExemptionId;
    }




}


