package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * WeeklyEffort generated by hbm2java
 */
public class WeeklyEffort  implements java.io.Serializable {


     private BigDecimal weeklyEffortId;
     private Project project;
     private BigDecimal plannedEffort;
     private Date startDate;

    public WeeklyEffort() {
    }

	
    public WeeklyEffort(BigDecimal weeklyEffortId) {
        this.weeklyEffortId = weeklyEffortId;
    }
    public WeeklyEffort(BigDecimal weeklyEffortId, Project project, BigDecimal plannedEffort, Date startDate) {
       this.weeklyEffortId = weeklyEffortId;
       this.project = project;
       this.plannedEffort = plannedEffort;
       this.startDate = startDate;
    }
   
    public BigDecimal getWeeklyEffortId() {
        return this.weeklyEffortId;
    }
    
    public void setWeeklyEffortId(BigDecimal weeklyEffortId) {
        this.weeklyEffortId = weeklyEffortId;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public BigDecimal getPlannedEffort() {
        return this.plannedEffort;
    }
    
    public void setPlannedEffort(BigDecimal plannedEffort) {
        this.plannedEffort = plannedEffort;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }




}


