package openones.oopms.model;
// Generated Jul 6, 2012 7:55:26 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project  implements java.io.Serializable {


     private BigDecimal projectId;
     private String type;
     private String code;
     private String name;
     private String groupName;
     private Date startDate;
     private BigDecimal perComplete;
     private String leader;
     private Date baseFinishDate;
     private Date planFinishDate;
     private Date actualFinishDate;
     private BigDecimal baseEffort;
     private BigDecimal planEffort;
     private BigDecimal actualEffort;
     private String description;
     private BigDecimal totalbug;
     private BigDecimal totalweightedbug;
     private BigDecimal totalrequirement;
     private BigDecimal committedrequirement;
     private BigDecimal designedrequirement;
     private BigDecimal codedrequirement;
     private BigDecimal testedrequirement;
     private BigDecimal deployedrequirement;
     private BigDecimal acceptedrequirement;
     private BigDecimal totaldefect;
     private BigDecimal totalweighteddefect;
     private BigDecimal fatalpendingdefect;
     private BigDecimal seriouspendingdefect;
     private BigDecimal mediumpendingdefect;
     private BigDecimal cosmeticpendingdefect;
     private BigDecimal totalfataldefect;
     private BigDecimal totalseriousdefect;
     private BigDecimal totalmediumdefect;
     private BigDecimal totalcosmeticdefect;
     private String status;
     private BigDecimal scheduleStatus;
     private BigDecimal effortStatus;
     private Date lastUpdate;
     private String category;
     private String customer;
     private Date planStartDate;
     private Boolean applyPpm;
     private String reason;
     private BigDecimal baseBillableEffort;
     private BigDecimal planBillableEffort;
     private BigDecimal actualBillableEffort;
     private String rank;
     private String customer2nd;
     private String projectLevel;
     private String divisionName;
     private BigDecimal archiveStatus;
     private BigDecimal parentId;
     private BigDecimal unitId;
     private String projectStatusCode;
     private String projectCategoryCode;
     private String projectTypeCode;
     private BigDecimal typeCustomer;
     private BigDecimal typeCustomer2nd;
     private Set assignments = new HashSet(0);
     private Set timesheets = new HashSet(0);

    public Project() {
    }

	
    public Project(BigDecimal projectId, String type, String code, String name) {
        this.projectId = projectId;
        this.type = type;
        this.code = code;
        this.name = name;
    }
    public Project(BigDecimal projectId, String type, String code, String name, String groupName, Date startDate, BigDecimal perComplete, String leader, Date baseFinishDate, Date planFinishDate, Date actualFinishDate, BigDecimal baseEffort, BigDecimal planEffort, BigDecimal actualEffort, String description, BigDecimal totalbug, BigDecimal totalweightedbug, BigDecimal totalrequirement, BigDecimal committedrequirement, BigDecimal designedrequirement, BigDecimal codedrequirement, BigDecimal testedrequirement, BigDecimal deployedrequirement, BigDecimal acceptedrequirement, BigDecimal totaldefect, BigDecimal totalweighteddefect, BigDecimal fatalpendingdefect, BigDecimal seriouspendingdefect, BigDecimal mediumpendingdefect, BigDecimal cosmeticpendingdefect, BigDecimal totalfataldefect, BigDecimal totalseriousdefect, BigDecimal totalmediumdefect, BigDecimal totalcosmeticdefect, String status, BigDecimal scheduleStatus, BigDecimal effortStatus, Date lastUpdate, String category, String customer, Date planStartDate, Boolean applyPpm, String reason, BigDecimal baseBillableEffort, BigDecimal planBillableEffort, BigDecimal actualBillableEffort, String rank, String customer2nd, String projectLevel, String divisionName, BigDecimal archiveStatus, BigDecimal parentId, BigDecimal unitId, String projectStatusCode, String projectCategoryCode, String projectTypeCode, BigDecimal typeCustomer, BigDecimal typeCustomer2nd, Set assignments, Set timesheets) {
       this.projectId = projectId;
       this.type = type;
       this.code = code;
       this.name = name;
       this.groupName = groupName;
       this.startDate = startDate;
       this.perComplete = perComplete;
       this.leader = leader;
       this.baseFinishDate = baseFinishDate;
       this.planFinishDate = planFinishDate;
       this.actualFinishDate = actualFinishDate;
       this.baseEffort = baseEffort;
       this.planEffort = planEffort;
       this.actualEffort = actualEffort;
       this.description = description;
       this.totalbug = totalbug;
       this.totalweightedbug = totalweightedbug;
       this.totalrequirement = totalrequirement;
       this.committedrequirement = committedrequirement;
       this.designedrequirement = designedrequirement;
       this.codedrequirement = codedrequirement;
       this.testedrequirement = testedrequirement;
       this.deployedrequirement = deployedrequirement;
       this.acceptedrequirement = acceptedrequirement;
       this.totaldefect = totaldefect;
       this.totalweighteddefect = totalweighteddefect;
       this.fatalpendingdefect = fatalpendingdefect;
       this.seriouspendingdefect = seriouspendingdefect;
       this.mediumpendingdefect = mediumpendingdefect;
       this.cosmeticpendingdefect = cosmeticpendingdefect;
       this.totalfataldefect = totalfataldefect;
       this.totalseriousdefect = totalseriousdefect;
       this.totalmediumdefect = totalmediumdefect;
       this.totalcosmeticdefect = totalcosmeticdefect;
       this.status = status;
       this.scheduleStatus = scheduleStatus;
       this.effortStatus = effortStatus;
       this.lastUpdate = lastUpdate;
       this.category = category;
       this.customer = customer;
       this.planStartDate = planStartDate;
       this.applyPpm = applyPpm;
       this.reason = reason;
       this.baseBillableEffort = baseBillableEffort;
       this.planBillableEffort = planBillableEffort;
       this.actualBillableEffort = actualBillableEffort;
       this.rank = rank;
       this.customer2nd = customer2nd;
       this.projectLevel = projectLevel;
       this.divisionName = divisionName;
       this.archiveStatus = archiveStatus;
       this.parentId = parentId;
       this.unitId = unitId;
       this.projectStatusCode = projectStatusCode;
       this.projectCategoryCode = projectCategoryCode;
       this.projectTypeCode = projectTypeCode;
       this.typeCustomer = typeCustomer;
       this.typeCustomer2nd = typeCustomer2nd;
       this.assignments = assignments;
       this.timesheets = timesheets;
    }
   
    public BigDecimal getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(BigDecimal projectId) {
        this.projectId = projectId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public BigDecimal getPerComplete() {
        return this.perComplete;
    }
    
    public void setPerComplete(BigDecimal perComplete) {
        this.perComplete = perComplete;
    }
    public String getLeader() {
        return this.leader;
    }
    
    public void setLeader(String leader) {
        this.leader = leader;
    }
    public Date getBaseFinishDate() {
        return this.baseFinishDate;
    }
    
    public void setBaseFinishDate(Date baseFinishDate) {
        this.baseFinishDate = baseFinishDate;
    }
    public Date getPlanFinishDate() {
        return this.planFinishDate;
    }
    
    public void setPlanFinishDate(Date planFinishDate) {
        this.planFinishDate = planFinishDate;
    }
    public Date getActualFinishDate() {
        return this.actualFinishDate;
    }
    
    public void setActualFinishDate(Date actualFinishDate) {
        this.actualFinishDate = actualFinishDate;
    }
    public BigDecimal getBaseEffort() {
        return this.baseEffort;
    }
    
    public void setBaseEffort(BigDecimal baseEffort) {
        this.baseEffort = baseEffort;
    }
    public BigDecimal getPlanEffort() {
        return this.planEffort;
    }
    
    public void setPlanEffort(BigDecimal planEffort) {
        this.planEffort = planEffort;
    }
    public BigDecimal getActualEffort() {
        return this.actualEffort;
    }
    
    public void setActualEffort(BigDecimal actualEffort) {
        this.actualEffort = actualEffort;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getTotalbug() {
        return this.totalbug;
    }
    
    public void setTotalbug(BigDecimal totalbug) {
        this.totalbug = totalbug;
    }
    public BigDecimal getTotalweightedbug() {
        return this.totalweightedbug;
    }
    
    public void setTotalweightedbug(BigDecimal totalweightedbug) {
        this.totalweightedbug = totalweightedbug;
    }
    public BigDecimal getTotalrequirement() {
        return this.totalrequirement;
    }
    
    public void setTotalrequirement(BigDecimal totalrequirement) {
        this.totalrequirement = totalrequirement;
    }
    public BigDecimal getCommittedrequirement() {
        return this.committedrequirement;
    }
    
    public void setCommittedrequirement(BigDecimal committedrequirement) {
        this.committedrequirement = committedrequirement;
    }
    public BigDecimal getDesignedrequirement() {
        return this.designedrequirement;
    }
    
    public void setDesignedrequirement(BigDecimal designedrequirement) {
        this.designedrequirement = designedrequirement;
    }
    public BigDecimal getCodedrequirement() {
        return this.codedrequirement;
    }
    
    public void setCodedrequirement(BigDecimal codedrequirement) {
        this.codedrequirement = codedrequirement;
    }
    public BigDecimal getTestedrequirement() {
        return this.testedrequirement;
    }
    
    public void setTestedrequirement(BigDecimal testedrequirement) {
        this.testedrequirement = testedrequirement;
    }
    public BigDecimal getDeployedrequirement() {
        return this.deployedrequirement;
    }
    
    public void setDeployedrequirement(BigDecimal deployedrequirement) {
        this.deployedrequirement = deployedrequirement;
    }
    public BigDecimal getAcceptedrequirement() {
        return this.acceptedrequirement;
    }
    
    public void setAcceptedrequirement(BigDecimal acceptedrequirement) {
        this.acceptedrequirement = acceptedrequirement;
    }
    public BigDecimal getTotaldefect() {
        return this.totaldefect;
    }
    
    public void setTotaldefect(BigDecimal totaldefect) {
        this.totaldefect = totaldefect;
    }
    public BigDecimal getTotalweighteddefect() {
        return this.totalweighteddefect;
    }
    
    public void setTotalweighteddefect(BigDecimal totalweighteddefect) {
        this.totalweighteddefect = totalweighteddefect;
    }
    public BigDecimal getFatalpendingdefect() {
        return this.fatalpendingdefect;
    }
    
    public void setFatalpendingdefect(BigDecimal fatalpendingdefect) {
        this.fatalpendingdefect = fatalpendingdefect;
    }
    public BigDecimal getSeriouspendingdefect() {
        return this.seriouspendingdefect;
    }
    
    public void setSeriouspendingdefect(BigDecimal seriouspendingdefect) {
        this.seriouspendingdefect = seriouspendingdefect;
    }
    public BigDecimal getMediumpendingdefect() {
        return this.mediumpendingdefect;
    }
    
    public void setMediumpendingdefect(BigDecimal mediumpendingdefect) {
        this.mediumpendingdefect = mediumpendingdefect;
    }
    public BigDecimal getCosmeticpendingdefect() {
        return this.cosmeticpendingdefect;
    }
    
    public void setCosmeticpendingdefect(BigDecimal cosmeticpendingdefect) {
        this.cosmeticpendingdefect = cosmeticpendingdefect;
    }
    public BigDecimal getTotalfataldefect() {
        return this.totalfataldefect;
    }
    
    public void setTotalfataldefect(BigDecimal totalfataldefect) {
        this.totalfataldefect = totalfataldefect;
    }
    public BigDecimal getTotalseriousdefect() {
        return this.totalseriousdefect;
    }
    
    public void setTotalseriousdefect(BigDecimal totalseriousdefect) {
        this.totalseriousdefect = totalseriousdefect;
    }
    public BigDecimal getTotalmediumdefect() {
        return this.totalmediumdefect;
    }
    
    public void setTotalmediumdefect(BigDecimal totalmediumdefect) {
        this.totalmediumdefect = totalmediumdefect;
    }
    public BigDecimal getTotalcosmeticdefect() {
        return this.totalcosmeticdefect;
    }
    
    public void setTotalcosmeticdefect(BigDecimal totalcosmeticdefect) {
        this.totalcosmeticdefect = totalcosmeticdefect;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public BigDecimal getScheduleStatus() {
        return this.scheduleStatus;
    }
    
    public void setScheduleStatus(BigDecimal scheduleStatus) {
        this.scheduleStatus = scheduleStatus;
    }
    public BigDecimal getEffortStatus() {
        return this.effortStatus;
    }
    
    public void setEffortStatus(BigDecimal effortStatus) {
        this.effortStatus = effortStatus;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(String customer) {
        this.customer = customer;
    }
    public Date getPlanStartDate() {
        return this.planStartDate;
    }
    
    public void setPlanStartDate(Date planStartDate) {
        this.planStartDate = planStartDate;
    }
    public Boolean getApplyPpm() {
        return this.applyPpm;
    }
    
    public void setApplyPpm(Boolean applyPpm) {
        this.applyPpm = applyPpm;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public BigDecimal getBaseBillableEffort() {
        return this.baseBillableEffort;
    }
    
    public void setBaseBillableEffort(BigDecimal baseBillableEffort) {
        this.baseBillableEffort = baseBillableEffort;
    }
    public BigDecimal getPlanBillableEffort() {
        return this.planBillableEffort;
    }
    
    public void setPlanBillableEffort(BigDecimal planBillableEffort) {
        this.planBillableEffort = planBillableEffort;
    }
    public BigDecimal getActualBillableEffort() {
        return this.actualBillableEffort;
    }
    
    public void setActualBillableEffort(BigDecimal actualBillableEffort) {
        this.actualBillableEffort = actualBillableEffort;
    }
    public String getRank() {
        return this.rank;
    }
    
    public void setRank(String rank) {
        this.rank = rank;
    }
    public String getCustomer2nd() {
        return this.customer2nd;
    }
    
    public void setCustomer2nd(String customer2nd) {
        this.customer2nd = customer2nd;
    }
    public String getProjectLevel() {
        return this.projectLevel;
    }
    
    public void setProjectLevel(String projectLevel) {
        this.projectLevel = projectLevel;
    }
    public String getDivisionName() {
        return this.divisionName;
    }
    
    public void setDivisionName(String divisionName) {
        this.divisionName = divisionName;
    }
    public BigDecimal getArchiveStatus() {
        return this.archiveStatus;
    }
    
    public void setArchiveStatus(BigDecimal archiveStatus) {
        this.archiveStatus = archiveStatus;
    }
    public BigDecimal getParentId() {
        return this.parentId;
    }
    
    public void setParentId(BigDecimal parentId) {
        this.parentId = parentId;
    }
    public BigDecimal getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(BigDecimal unitId) {
        this.unitId = unitId;
    }
    public String getProjectStatusCode() {
        return this.projectStatusCode;
    }
    
    public void setProjectStatusCode(String projectStatusCode) {
        this.projectStatusCode = projectStatusCode;
    }
    public String getProjectCategoryCode() {
        return this.projectCategoryCode;
    }
    
    public void setProjectCategoryCode(String projectCategoryCode) {
        this.projectCategoryCode = projectCategoryCode;
    }
    public String getProjectTypeCode() {
        return this.projectTypeCode;
    }
    
    public void setProjectTypeCode(String projectTypeCode) {
        this.projectTypeCode = projectTypeCode;
    }
    public BigDecimal getTypeCustomer() {
        return this.typeCustomer;
    }
    
    public void setTypeCustomer(BigDecimal typeCustomer) {
        this.typeCustomer = typeCustomer;
    }
    public BigDecimal getTypeCustomer2nd() {
        return this.typeCustomer2nd;
    }
    
    public void setTypeCustomer2nd(BigDecimal typeCustomer2nd) {
        this.typeCustomer2nd = typeCustomer2nd;
    }
    public Set getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(Set assignments) {
        this.assignments = assignments;
    }
    public Set getTimesheets() {
        return this.timesheets;
    }
    
    public void setTimesheets(Set timesheets) {
        this.timesheets = timesheets;
    }




}


