package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Constraints generated by hbm2java
 */
public class Constraints  implements java.io.Serializable {


     private BigDecimal constraintId;
     private ProjectPlan projectPlan;
     private String description;
     private BigDecimal constraintType;
     private BigDecimal isConstraint;
     private String note;

    public Constraints() {
    }

	
    public Constraints(BigDecimal constraintId, BigDecimal isConstraint) {
        this.constraintId = constraintId;
        this.isConstraint = isConstraint;
    }
    public Constraints(BigDecimal constraintId, ProjectPlan projectPlan, String description, BigDecimal constraintType, BigDecimal isConstraint, String note) {
       this.constraintId = constraintId;
       this.projectPlan = projectPlan;
       this.description = description;
       this.constraintType = constraintType;
       this.isConstraint = isConstraint;
       this.note = note;
    }
   
    public BigDecimal getConstraintId() {
        return this.constraintId;
    }
    
    public void setConstraintId(BigDecimal constraintId) {
        this.constraintId = constraintId;
    }
    public ProjectPlan getProjectPlan() {
        return this.projectPlan;
    }
    
    public void setProjectPlan(ProjectPlan projectPlan) {
        this.projectPlan = projectPlan;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getConstraintType() {
        return this.constraintType;
    }
    
    public void setConstraintType(BigDecimal constraintType) {
        this.constraintType = constraintType;
    }
    public BigDecimal getIsConstraint() {
        return this.isConstraint;
    }
    
    public void setIsConstraint(BigDecimal isConstraint) {
        this.isConstraint = isConstraint;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


