package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * DefectStatus generated by hbm2java
 */
public class DefectStatus  implements java.io.Serializable {


     private BigDecimal dsId;
     private String name;

    public DefectStatus() {
    }

    public DefectStatus(BigDecimal dsId, String name) {
       this.dsId = dsId;
       this.name = name;
    }
   
    public BigDecimal getDsId() {
        return this.dsId;
    }
    
    public void setDsId(BigDecimal dsId) {
        this.dsId = dsId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


