package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * HelpId generated by hbm2java
 */
public class HelpId  implements java.io.Serializable {


     private String topic;
     private BigDecimal seq;

    public HelpId() {
    }

    public HelpId(String topic, BigDecimal seq) {
       this.topic = topic;
       this.seq = seq;
    }
   
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }
    public BigDecimal getSeq() {
        return this.seq;
    }
    
    public void setSeq(BigDecimal seq) {
        this.seq = seq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HelpId) ) return false;
		 HelpId castOther = ( HelpId ) other; 
         
		 return ( (this.getTopic()==castOther.getTopic()) || ( this.getTopic()!=null && castOther.getTopic()!=null && this.getTopic().equals(castOther.getTopic()) ) )
 && ( (this.getSeq()==castOther.getSeq()) || ( this.getSeq()!=null && castOther.getSeq()!=null && this.getSeq().equals(castOther.getSeq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTopic() == null ? 0 : this.getTopic().hashCode() );
         result = 37 * result + ( getSeq() == null ? 0 : this.getSeq().hashCode() );
         return result;
   }   


}


