package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * MeasurementsProgram generated by hbm2java
 */
public class MeasurementsProgram  implements java.io.Serializable {


     private BigDecimal mesId;
     private BigDecimal mesPrjId;
     private String mesDataColect;
     private String mesPurpose;
     private String mesResponsible;
     private String mesWhen;

    public MeasurementsProgram() {
    }

    public MeasurementsProgram(BigDecimal mesId, BigDecimal mesPrjId, String mesDataColect, String mesPurpose, String mesResponsible, String mesWhen) {
       this.mesId = mesId;
       this.mesPrjId = mesPrjId;
       this.mesDataColect = mesDataColect;
       this.mesPurpose = mesPurpose;
       this.mesResponsible = mesResponsible;
       this.mesWhen = mesWhen;
    }
   
    public BigDecimal getMesId() {
        return this.mesId;
    }
    
    public void setMesId(BigDecimal mesId) {
        this.mesId = mesId;
    }
    public BigDecimal getMesPrjId() {
        return this.mesPrjId;
    }
    
    public void setMesPrjId(BigDecimal mesPrjId) {
        this.mesPrjId = mesPrjId;
    }
    public String getMesDataColect() {
        return this.mesDataColect;
    }
    
    public void setMesDataColect(String mesDataColect) {
        this.mesDataColect = mesDataColect;
    }
    public String getMesPurpose() {
        return this.mesPurpose;
    }
    
    public void setMesPurpose(String mesPurpose) {
        this.mesPurpose = mesPurpose;
    }
    public String getMesResponsible() {
        return this.mesResponsible;
    }
    
    public void setMesResponsible(String mesResponsible) {
        this.mesResponsible = mesResponsible;
    }
    public String getMesWhen() {
        return this.mesWhen;
    }
    
    public void setMesWhen(String mesWhen) {
        this.mesWhen = mesWhen;
    }




}


