package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * PlansQcStage generated by hbm2java
 */
public class PlansQcStage  implements java.io.Serializable {


     private PlansQcStageId id;
     private Milestone milestone;
     private BigDecimal plan;
     private BigDecimal replan;
     private BigDecimal replanDefectRate;

    public PlansQcStage() {
    }

	
    public PlansQcStage(PlansQcStageId id, Milestone milestone) {
        this.id = id;
        this.milestone = milestone;
    }
    public PlansQcStage(PlansQcStageId id, Milestone milestone, BigDecimal plan, BigDecimal replan, BigDecimal replanDefectRate) {
       this.id = id;
       this.milestone = milestone;
       this.plan = plan;
       this.replan = replan;
       this.replanDefectRate = replanDefectRate;
    }
   
    public PlansQcStageId getId() {
        return this.id;
    }
    
    public void setId(PlansQcStageId id) {
        this.id = id;
    }
    public Milestone getMilestone() {
        return this.milestone;
    }
    
    public void setMilestone(Milestone milestone) {
        this.milestone = milestone;
    }
    public BigDecimal getPlan() {
        return this.plan;
    }
    
    public void setPlan(BigDecimal plan) {
        this.plan = plan;
    }
    public BigDecimal getReplan() {
        return this.replan;
    }
    
    public void setReplan(BigDecimal replan) {
        this.replan = replan;
    }
    public BigDecimal getReplanDefectRate() {
        return this.replanDefectRate;
    }
    
    public void setReplanDefectRate(BigDecimal replanDefectRate) {
        this.replanDefectRate = replanDefectRate;
    }




}


