package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * RiskSource generated by hbm2java
 */
public class RiskSource  implements java.io.Serializable {


     private BigDecimal sourceId;
     private RiskCategory riskCategory;
     private String sourceName;
     private BigDecimal topRisk;
     private BigDecimal processId;

    public RiskSource() {
    }

	
    public RiskSource(BigDecimal sourceId, RiskCategory riskCategory) {
        this.sourceId = sourceId;
        this.riskCategory = riskCategory;
    }
    public RiskSource(BigDecimal sourceId, RiskCategory riskCategory, String sourceName, BigDecimal topRisk, BigDecimal processId) {
       this.sourceId = sourceId;
       this.riskCategory = riskCategory;
       this.sourceName = sourceName;
       this.topRisk = topRisk;
       this.processId = processId;
    }
   
    public BigDecimal getSourceId() {
        return this.sourceId;
    }
    
    public void setSourceId(BigDecimal sourceId) {
        this.sourceId = sourceId;
    }
    public RiskCategory getRiskCategory() {
        return this.riskCategory;
    }
    
    public void setRiskCategory(RiskCategory riskCategory) {
        this.riskCategory = riskCategory;
    }
    public String getSourceName() {
        return this.sourceName;
    }
    
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName;
    }
    public BigDecimal getTopRisk() {
        return this.topRisk;
    }
    
    public void setTopRisk(BigDecimal topRisk) {
        this.topRisk = topRisk;
    }
    public BigDecimal getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(BigDecimal processId) {
        this.processId = processId;
    }




}


