package openones.oopms.projecteye.model;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Process generated by hbm2java
 */
public class Process  implements java.io.Serializable {


     private String code;
     private String name;
     private BigDecimal processId;
     private Byte disabled;
     private String appName;
     private Set workproducts = new HashSet(0);
     private Set qcActivities = new HashSet(0);

    public Process() {
    }

	
    public Process(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public Process(String code, String name, BigDecimal processId, Byte disabled, String appName, Set workproducts, Set qcActivities) {
       this.code = code;
       this.name = name;
       this.processId = processId;
       this.disabled = disabled;
       this.appName = appName;
       this.workproducts = workproducts;
       this.qcActivities = qcActivities;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(BigDecimal processId) {
        this.processId = processId;
    }
    public Byte getDisabled() {
        return this.disabled;
    }
    
    public void setDisabled(Byte disabled) {
        this.disabled = disabled;
    }
    public String getAppName() {
        return this.appName;
    }
    
    public void setAppName(String appName) {
        this.appName = appName;
    }
    public Set getWorkproducts() {
        return this.workproducts;
    }
    
    public void setWorkproducts(Set workproducts) {
        this.workproducts = workproducts;
    }
    public Set getQcActivities() {
        return this.qcActivities;
    }
    
    public void setQcActivities(Set qcActivities) {
        this.qcActivities = qcActivities;
    }




}


