package openones.oopms.model;
// Generated Jul 6, 2012 2:17:18 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Tasks generated by hbm2java
 */
public class Tasks  implements java.io.Serializable {


     private BigDecimal taskid;
     private Workunit workunit;
     private String description;
     private BigDecimal assignedto;
     private BigDecimal effort;
     private Date planDate;
     private Date actualDate;
     private boolean status;
     private byte type;
     private String note;
     private Short process;
     private Date replanDate;
     private Boolean feasible;
     private String code;

    public Tasks() {
    }

	
    public Tasks(BigDecimal taskid, Workunit workunit, String description, BigDecimal assignedto, Date planDate, boolean status, byte type) {
        this.taskid = taskid;
        this.workunit = workunit;
        this.description = description;
        this.assignedto = assignedto;
        this.planDate = planDate;
        this.status = status;
        this.type = type;
    }
    public Tasks(BigDecimal taskid, Workunit workunit, String description, BigDecimal assignedto, BigDecimal effort, Date planDate, Date actualDate, boolean status, byte type, String note, Short process, Date replanDate, Boolean feasible, String code) {
       this.taskid = taskid;
       this.workunit = workunit;
       this.description = description;
       this.assignedto = assignedto;
       this.effort = effort;
       this.planDate = planDate;
       this.actualDate = actualDate;
       this.status = status;
       this.type = type;
       this.note = note;
       this.process = process;
       this.replanDate = replanDate;
       this.feasible = feasible;
       this.code = code;
    }
   
    public BigDecimal getTaskid() {
        return this.taskid;
    }
    
    public void setTaskid(BigDecimal taskid) {
        this.taskid = taskid;
    }
    public Workunit getWorkunit() {
        return this.workunit;
    }
    
    public void setWorkunit(Workunit workunit) {
        this.workunit = workunit;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getAssignedto() {
        return this.assignedto;
    }
    
    public void setAssignedto(BigDecimal assignedto) {
        this.assignedto = assignedto;
    }
    public BigDecimal getEffort() {
        return this.effort;
    }
    
    public void setEffort(BigDecimal effort) {
        this.effort = effort;
    }
    public Date getPlanDate() {
        return this.planDate;
    }
    
    public void setPlanDate(Date planDate) {
        this.planDate = planDate;
    }
    public Date getActualDate() {
        return this.actualDate;
    }
    
    public void setActualDate(Date actualDate) {
        this.actualDate = actualDate;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Short getProcess() {
        return this.process;
    }
    
    public void setProcess(Short process) {
        this.process = process;
    }
    public Date getReplanDate() {
        return this.replanDate;
    }
    
    public void setReplanDate(Date replanDate) {
        this.replanDate = replanDate;
    }
    public Boolean getFeasible() {
        return this.feasible;
    }
    
    public void setFeasible(Boolean feasible) {
        this.feasible = feasible;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }




}


