package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ApplicationType generated by hbm2java
 */
public class ApplicationType  implements java.io.Serializable {


     private BigDecimal applicationId;
     private String typeName;
     private String status;
     private Set projectPlans = new HashSet(0);

    public ApplicationType() {
    }

	
    public ApplicationType(BigDecimal applicationId, String typeName) {
        this.applicationId = applicationId;
        this.typeName = typeName;
    }
    public ApplicationType(BigDecimal applicationId, String typeName, String status, Set projectPlans) {
       this.applicationId = applicationId;
       this.typeName = typeName;
       this.status = status;
       this.projectPlans = projectPlans;
    }
   
    public BigDecimal getApplicationId() {
        return this.applicationId;
    }
    
    public void setApplicationId(BigDecimal applicationId) {
        this.applicationId = applicationId;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getProjectPlans() {
        return this.projectPlans;
    }
    
    public void setProjectPlans(Set projectPlans) {
        this.projectPlans = projectPlans;
    }




}


