package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Conversion generated by hbm2java
 */
public class Conversion  implements java.io.Serializable {


     private BigDecimal conversionId;
     private EstimationMethod estimationMethod;
     private Language language;
     private BigDecimal sloc;
     private Date lastUpdate;
     private String note;

    public Conversion() {
    }

	
    public Conversion(BigDecimal conversionId) {
        this.conversionId = conversionId;
    }
    public Conversion(BigDecimal conversionId, EstimationMethod estimationMethod, Language language, BigDecimal sloc, Date lastUpdate, String note) {
       this.conversionId = conversionId;
       this.estimationMethod = estimationMethod;
       this.language = language;
       this.sloc = sloc;
       this.lastUpdate = lastUpdate;
       this.note = note;
    }
   
    public BigDecimal getConversionId() {
        return this.conversionId;
    }
    
    public void setConversionId(BigDecimal conversionId) {
        this.conversionId = conversionId;
    }
    public EstimationMethod getEstimationMethod() {
        return this.estimationMethod;
    }
    
    public void setEstimationMethod(EstimationMethod estimationMethod) {
        this.estimationMethod = estimationMethod;
    }
    public Language getLanguage() {
        return this.language;
    }
    
    public void setLanguage(Language language) {
        this.language = language;
    }
    public BigDecimal getSloc() {
        return this.sloc;
    }
    
    public void setSloc(BigDecimal sloc) {
        this.sloc = sloc;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


