package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA

/**
 * DefectPriority generated by hbm2java
 */
public class DefectPriority implements java.io.Serializable {

    private long dpId;
    private String name;

    public DefectPriority() {
    }

    public DefectPriority(long dpId, String name) {
        this.dpId = dpId;
        this.name = name;
    }

    public long getDpId() {
        return this.dpId;
    }

    public void setDpId(long dpId) {
        this.dpId = dpId;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
