package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * DefectDistributionByProcess generated by hbm2java
 */
public class DefectDistributionByProcess  implements java.io.Serializable {


     private DefectDistributionByProcessId id;
     private BigDecimal value;

    public DefectDistributionByProcess() {
    }

	
    public DefectDistributionByProcess(DefectDistributionByProcessId id) {
        this.id = id;
    }
    public DefectDistributionByProcess(DefectDistributionByProcessId id, BigDecimal value) {
       this.id = id;
       this.value = value;
    }
   
    public DefectDistributionByProcessId getId() {
        return this.id;
    }
    
    public void setId(DefectDistributionByProcessId id) {
        this.id = id;
    }
    public BigDecimal getValue() {
        return this.value;
    }
    
    public void setValue(BigDecimal value) {
        this.value = value;
    }




}


