package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * DefectType generated by hbm2java
 */
public class DefectType  implements java.io.Serializable {


     private BigDecimal dtId;
     private String name;

    public DefectType() {
    }

    public DefectType(BigDecimal dtId, String name) {
       this.dtId = dtId;
       this.name = name;
    }
   
    public BigDecimal getDtId() {
        return this.dtId;
    }
    
    public void setDtId(BigDecimal dtId) {
        this.dtId = dtId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


