package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Developer generated by hbm2java
 */
public class Developer  implements java.io.Serializable {


     private BigDecimal developerId;
     private String name;
     private String groupName;
     private String account;
     private String designation;
     private String role;
     private String password;
     private BigDecimal status;
     private String email;
     private Date beginDate;
     private Date quitDate;
     private String orgPositionCode;
     private BigDecimal unitId;
     private String userTypeCode;
     private String location;
     private String phoneNo;
     private String alternativeEmail;
     private String passwordHint;
     private Boolean disabled;
     private Date passwordDate;
     private Boolean changePw;
     private Character accountExpired;
     private Character accountLocked;
     private Character credentialsExpired;
     private String passwordBackup;
     private String staffId;
     private Set timesheetArchives = new HashSet(0);
     private Set timesheets = new HashSet(0);
     private Set teams = new HashSet(0);
     private Set timesheetExemptions = new HashSet(0);
     private Set timesheetOldDatas = new HashSet(0);
     private Set groupses = new HashSet(0);
     private Set defectAttachments = new HashSet(0);
     private Set assignments = new HashSet(0);
     private Set otherAssignments = new HashSet(0);
     private Set milestones = new HashSet(0);
     private Set defectQueries = new HashSet(0);
     private Set pcbs = new HashSet(0);
     private Set risks = new HashSet(0);
     private Set darPlans = new HashSet(0);

    public Developer() {
    }

	
    public Developer(BigDecimal developerId, String name, String groupName) {
        this.developerId = developerId;
        this.name = name;
        this.groupName = groupName;
    }
    public Developer(BigDecimal developerId, String name, String groupName, String account, String designation, String role, String password, BigDecimal status, String email, Date beginDate, Date quitDate, String orgPositionCode, BigDecimal unitId, String userTypeCode, String location, String phoneNo, String alternativeEmail, String passwordHint, Boolean disabled, Date passwordDate, Boolean changePw, Character accountExpired, Character accountLocked, Character credentialsExpired, String passwordBackup, String staffId, Set timesheetArchives, Set timesheets, Set teams, Set timesheetExemptions, Set timesheetOldDatas, Set groupses, Set defectAttachments, Set assignments, Set otherAssignments, Set milestones, Set defectQueries, Set pcbs, Set risks, Set darPlans) {
       this.developerId = developerId;
       this.name = name;
       this.groupName = groupName;
       this.account = account;
       this.designation = designation;
       this.role = role;
       this.password = password;
       this.status = status;
       this.email = email;
       this.beginDate = beginDate;
       this.quitDate = quitDate;
       this.orgPositionCode = orgPositionCode;
       this.unitId = unitId;
       this.userTypeCode = userTypeCode;
       this.location = location;
       this.phoneNo = phoneNo;
       this.alternativeEmail = alternativeEmail;
       this.passwordHint = passwordHint;
       this.disabled = disabled;
       this.passwordDate = passwordDate;
       this.changePw = changePw;
       this.accountExpired = accountExpired;
       this.accountLocked = accountLocked;
       this.credentialsExpired = credentialsExpired;
       this.passwordBackup = passwordBackup;
       this.staffId = staffId;
       this.timesheetArchives = timesheetArchives;
       this.timesheets = timesheets;
       this.teams = teams;
       this.timesheetExemptions = timesheetExemptions;
       this.timesheetOldDatas = timesheetOldDatas;
       this.groupses = groupses;
       this.defectAttachments = defectAttachments;
       this.assignments = assignments;
       this.otherAssignments = otherAssignments;
       this.milestones = milestones;
       this.defectQueries = defectQueries;
       this.pcbs = pcbs;
       this.risks = risks;
       this.darPlans = darPlans;
    }
   
    public BigDecimal getDeveloperId() {
        return this.developerId;
    }
    
    public void setDeveloperId(BigDecimal developerId) {
        this.developerId = developerId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getAccount() {
        return this.account;
    }
    
    public void setAccount(String account) {
        this.account = account;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }
    public Date getQuitDate() {
        return this.quitDate;
    }
    
    public void setQuitDate(Date quitDate) {
        this.quitDate = quitDate;
    }
    public String getOrgPositionCode() {
        return this.orgPositionCode;
    }
    
    public void setOrgPositionCode(String orgPositionCode) {
        this.orgPositionCode = orgPositionCode;
    }
    public BigDecimal getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(BigDecimal unitId) {
        this.unitId = unitId;
    }
    public String getUserTypeCode() {
        return this.userTypeCode;
    }
    
    public void setUserTypeCode(String userTypeCode) {
        this.userTypeCode = userTypeCode;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
    public String getAlternativeEmail() {
        return this.alternativeEmail;
    }
    
    public void setAlternativeEmail(String alternativeEmail) {
        this.alternativeEmail = alternativeEmail;
    }
    public String getPasswordHint() {
        return this.passwordHint;
    }
    
    public void setPasswordHint(String passwordHint) {
        this.passwordHint = passwordHint;
    }
    public Boolean getDisabled() {
        return this.disabled;
    }
    
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }
    public Date getPasswordDate() {
        return this.passwordDate;
    }
    
    public void setPasswordDate(Date passwordDate) {
        this.passwordDate = passwordDate;
    }
    public Boolean getChangePw() {
        return this.changePw;
    }
    
    public void setChangePw(Boolean changePw) {
        this.changePw = changePw;
    }
    public Character getAccountExpired() {
        return this.accountExpired;
    }
    
    public void setAccountExpired(Character accountExpired) {
        this.accountExpired = accountExpired;
    }
    public Character getAccountLocked() {
        return this.accountLocked;
    }
    
    public void setAccountLocked(Character accountLocked) {
        this.accountLocked = accountLocked;
    }
    public Character getCredentialsExpired() {
        return this.credentialsExpired;
    }
    
    public void setCredentialsExpired(Character credentialsExpired) {
        this.credentialsExpired = credentialsExpired;
    }
    public String getPasswordBackup() {
        return this.passwordBackup;
    }
    
    public void setPasswordBackup(String passwordBackup) {
        this.passwordBackup = passwordBackup;
    }
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }
    public Set getTimesheetArchives() {
        return this.timesheetArchives;
    }
    
    public void setTimesheetArchives(Set timesheetArchives) {
        this.timesheetArchives = timesheetArchives;
    }
    public Set getTimesheets() {
        return this.timesheets;
    }
    
    public void setTimesheets(Set timesheets) {
        this.timesheets = timesheets;
    }
    public Set getTeams() {
        return this.teams;
    }
    
    public void setTeams(Set teams) {
        this.teams = teams;
    }
    public Set getTimesheetExemptions() {
        return this.timesheetExemptions;
    }
    
    public void setTimesheetExemptions(Set timesheetExemptions) {
        this.timesheetExemptions = timesheetExemptions;
    }
    public Set getTimesheetOldDatas() {
        return this.timesheetOldDatas;
    }
    
    public void setTimesheetOldDatas(Set timesheetOldDatas) {
        this.timesheetOldDatas = timesheetOldDatas;
    }
    public Set getGroupses() {
        return this.groupses;
    }
    
    public void setGroupses(Set groupses) {
        this.groupses = groupses;
    }
    public Set getDefectAttachments() {
        return this.defectAttachments;
    }
    
    public void setDefectAttachments(Set defectAttachments) {
        this.defectAttachments = defectAttachments;
    }
    public Set getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(Set assignments) {
        this.assignments = assignments;
    }
    public Set getOtherAssignments() {
        return this.otherAssignments;
    }
    
    public void setOtherAssignments(Set otherAssignments) {
        this.otherAssignments = otherAssignments;
    }
    public Set getMilestones() {
        return this.milestones;
    }
    
    public void setMilestones(Set milestones) {
        this.milestones = milestones;
    }
    public Set getDefectQueries() {
        return this.defectQueries;
    }
    
    public void setDefectQueries(Set defectQueries) {
        this.defectQueries = defectQueries;
    }
    public Set getPcbs() {
        return this.pcbs;
    }
    
    public void setPcbs(Set pcbs) {
        this.pcbs = pcbs;
    }
    public Set getRisks() {
        return this.risks;
    }
    
    public void setRisks(Set risks) {
        this.risks = risks;
    }
    public Set getDarPlans() {
        return this.darPlans;
    }
    
    public void setDarPlans(Set darPlans) {
        this.darPlans = darPlans;
    }




}


