package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * EstimationMethod generated by hbm2java
 */
public class EstimationMethod  implements java.io.Serializable {


     private BigDecimal methodId;
     private String name;
     private String note;
     private BigDecimal isrelevant;
     private Set conversions = new HashSet(0);

    public EstimationMethod() {
    }

	
    public EstimationMethod(BigDecimal methodId) {
        this.methodId = methodId;
    }
    public EstimationMethod(BigDecimal methodId, String name, String note, BigDecimal isrelevant, Set conversions) {
       this.methodId = methodId;
       this.name = name;
       this.note = note;
       this.isrelevant = isrelevant;
       this.conversions = conversions;
    }
   
    public BigDecimal getMethodId() {
        return this.methodId;
    }
    
    public void setMethodId(BigDecimal methodId) {
        this.methodId = methodId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public BigDecimal getIsrelevant() {
        return this.isrelevant;
    }
    
    public void setIsrelevant(BigDecimal isrelevant) {
        this.isrelevant = isrelevant;
    }
    public Set getConversions() {
        return this.conversions;
    }
    
    public void setConversions(Set conversions) {
        this.conversions = conversions;
    }




}


