package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {


     private BigDecimal groupId;
     private Developer developer;
     private String groupname;
     private BigDecimal isoperationgroup;
     private String description;

    public Groups() {
    }

	
    public Groups(BigDecimal groupId, String groupname) {
        this.groupId = groupId;
        this.groupname = groupname;
    }
    public Groups(BigDecimal groupId, Developer developer, String groupname, BigDecimal isoperationgroup, String description) {
       this.groupId = groupId;
       this.developer = developer;
       this.groupname = groupname;
       this.isoperationgroup = isoperationgroup;
       this.description = description;
    }
   
    public BigDecimal getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(BigDecimal groupId) {
        this.groupId = groupId;
    }
    public Developer getDeveloper() {
        return this.developer;
    }
    
    public void setDeveloper(Developer developer) {
        this.developer = developer;
    }
    public String getGroupname() {
        return this.groupname;
    }
    
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }
    public BigDecimal getIsoperationgroup() {
        return this.isoperationgroup;
    }
    
    public void setIsoperationgroup(BigDecimal isoperationgroup) {
        this.isoperationgroup = isoperationgroup;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


