package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
public class Language  implements java.io.Serializable {


     private BigDecimal languageId;
     private String name;
     private String note;
     private Date convLastUpdate;
     private String sizeUnit;
     private BigDecimal isrelevant;
     private Set productLocActuals = new HashSet(0);
     private Set conversions = new HashSet(0);
     private Set productLocPlans = new HashSet(0);

    public Language() {
    }

	
    public Language(BigDecimal languageId, String sizeUnit) {
        this.languageId = languageId;
        this.sizeUnit = sizeUnit;
    }
    public Language(BigDecimal languageId, String name, String note, Date convLastUpdate, String sizeUnit, BigDecimal isrelevant, Set productLocActuals, Set conversions, Set productLocPlans) {
       this.languageId = languageId;
       this.name = name;
       this.note = note;
       this.convLastUpdate = convLastUpdate;
       this.sizeUnit = sizeUnit;
       this.isrelevant = isrelevant;
       this.productLocActuals = productLocActuals;
       this.conversions = conversions;
       this.productLocPlans = productLocPlans;
    }
   
    public BigDecimal getLanguageId() {
        return this.languageId;
    }
    
    public void setLanguageId(BigDecimal languageId) {
        this.languageId = languageId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Date getConvLastUpdate() {
        return this.convLastUpdate;
    }
    
    public void setConvLastUpdate(Date convLastUpdate) {
        this.convLastUpdate = convLastUpdate;
    }
    public String getSizeUnit() {
        return this.sizeUnit;
    }
    
    public void setSizeUnit(String sizeUnit) {
        this.sizeUnit = sizeUnit;
    }
    public BigDecimal getIsrelevant() {
        return this.isrelevant;
    }
    
    public void setIsrelevant(BigDecimal isrelevant) {
        this.isrelevant = isrelevant;
    }
    public Set getProductLocActuals() {
        return this.productLocActuals;
    }
    
    public void setProductLocActuals(Set productLocActuals) {
        this.productLocActuals = productLocActuals;
    }
    public Set getConversions() {
        return this.conversions;
    }
    
    public void setConversions(Set conversions) {
        this.conversions = conversions;
    }
    public Set getProductLocPlans() {
        return this.productLocPlans;
    }
    
    public void setProductLocPlans(Set productLocPlans) {
        this.productLocPlans = productLocPlans;
    }




}


