package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Lifecycle generated by hbm2java
 */
public class Lifecycle  implements java.io.Serializable {


     private BigDecimal lifecycleId;
     private String name;
     private Set normplans = new HashSet(0);

    public Lifecycle() {
    }

	
    public Lifecycle(BigDecimal lifecycleId) {
        this.lifecycleId = lifecycleId;
    }
    public Lifecycle(BigDecimal lifecycleId, String name, Set normplans) {
       this.lifecycleId = lifecycleId;
       this.name = name;
       this.normplans = normplans;
    }
   
    public BigDecimal getLifecycleId() {
        return this.lifecycleId;
    }
    
    public void setLifecycleId(BigDecimal lifecycleId) {
        this.lifecycleId = lifecycleId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getNormplans() {
        return this.normplans;
    }
    
    public void setNormplans(Set normplans) {
        this.normplans = normplans;
    }




}


