package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Nchistory generated by hbm2java
 */
public class Nchistory  implements java.io.Serializable {


     private BigDecimal ncid;
     private String history;

    public Nchistory() {
    }

	
    public Nchistory(BigDecimal ncid) {
        this.ncid = ncid;
    }
    public Nchistory(BigDecimal ncid, String history) {
       this.ncid = ncid;
       this.history = history;
    }
   
    public BigDecimal getNcid() {
        return this.ncid;
    }
    
    public void setNcid(BigDecimal ncid) {
        this.ncid = ncid;
    }
    public String getHistory() {
        return this.history;
    }
    
    public void setHistory(String history) {
        this.history = history;
    }




}


