package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * ProjectSchedule generated by hbm2java
 */
public class ProjectSchedule  implements java.io.Serializable {


     private BigDecimal schedId;
     private BigDecimal schedPrjId;
     private String schedActivity;
     private Date schedStartdate;
     private String schedResponsible;
     private String schedNote;
     private BigDecimal schedType;

    public ProjectSchedule() {
    }

	
    public ProjectSchedule(BigDecimal schedId, BigDecimal schedPrjId, String schedActivity, Date schedStartdate, BigDecimal schedType) {
        this.schedId = schedId;
        this.schedPrjId = schedPrjId;
        this.schedActivity = schedActivity;
        this.schedStartdate = schedStartdate;
        this.schedType = schedType;
    }
    public ProjectSchedule(BigDecimal schedId, BigDecimal schedPrjId, String schedActivity, Date schedStartdate, String schedResponsible, String schedNote, BigDecimal schedType) {
       this.schedId = schedId;
       this.schedPrjId = schedPrjId;
       this.schedActivity = schedActivity;
       this.schedStartdate = schedStartdate;
       this.schedResponsible = schedResponsible;
       this.schedNote = schedNote;
       this.schedType = schedType;
    }
   
    public BigDecimal getSchedId() {
        return this.schedId;
    }
    
    public void setSchedId(BigDecimal schedId) {
        this.schedId = schedId;
    }
    public BigDecimal getSchedPrjId() {
        return this.schedPrjId;
    }
    
    public void setSchedPrjId(BigDecimal schedPrjId) {
        this.schedPrjId = schedPrjId;
    }
    public String getSchedActivity() {
        return this.schedActivity;
    }
    
    public void setSchedActivity(String schedActivity) {
        this.schedActivity = schedActivity;
    }
    public Date getSchedStartdate() {
        return this.schedStartdate;
    }
    
    public void setSchedStartdate(Date schedStartdate) {
        this.schedStartdate = schedStartdate;
    }
    public String getSchedResponsible() {
        return this.schedResponsible;
    }
    
    public void setSchedResponsible(String schedResponsible) {
        this.schedResponsible = schedResponsible;
    }
    public String getSchedNote() {
        return this.schedNote;
    }
    
    public void setSchedNote(String schedNote) {
        this.schedNote = schedNote;
    }
    public BigDecimal getSchedType() {
        return this.schedType;
    }
    
    public void setSchedType(BigDecimal schedType) {
        this.schedType = schedType;
    }




}


