package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ProjectDatabase generated by hbm2java
 */
public class ProjectDatabase  implements java.io.Serializable {


     private BigDecimal projectId;
     private byte[] excelFile;

    public ProjectDatabase() {
    }

	
    public ProjectDatabase(BigDecimal projectId) {
        this.projectId = projectId;
    }
    public ProjectDatabase(BigDecimal projectId, byte[] excelFile) {
       this.projectId = projectId;
       this.excelFile = excelFile;
    }
   
    public BigDecimal getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(BigDecimal projectId) {
        this.projectId = projectId;
    }
    public byte[] getExcelFile() {
        return this.excelFile;
    }
    
    public void setExcelFile(byte[] excelFile) {
        this.excelFile = excelFile;
    }




}


