package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProjectPlan generated by hbm2java
 */
public class ProjectPlan  implements java.io.Serializable {


     private BigDecimal projectPlanId;
     private Project project;
     private ApplicationType applicationType;
     private Date lastUpdate;
     private BigDecimal managementEffort;
     private BigDecimal qualityEffort;
     private String schedule;
     private Clob structure;
     private Clob projectCommunication;
     private Clob managementCommunication;
     private Clob customerCommunication;
     private Clob otherCommunication;
     private Clob qualityObjectiveStrategy;
     private String configurationManagement;
     private BigDecimal maxTeamSize;
     private BigDecimal timeliness;
     private String customerLocation;
     private String domain;
     private String director;
     private Clob scopeObjective;
     private Clob asset;
     private Clob problem;
     private Clob rewardPenalty;
     private Clob orgStructure;
     private BigDecimal reqplanreviewdefect;
     private BigDecimal reqreplanreviewdefect;
     private BigDecimal desplanreviewdefect;
     private BigDecimal desreplanreviewdefect;
     private BigDecimal codplanreviewdefect;
     private BigDecimal codreplanreviewdefect;
     private BigDecimal othplanreviewdefect;
     private BigDecimal othreplanreviewdefect;
     private BigDecimal reqplantestdefect;
     private BigDecimal reqreplantestdefect;
     private BigDecimal desplantestdefect;
     private BigDecimal desreplantestdefect;
     private BigDecimal codplantestdefect;
     private BigDecimal codreplantestdefect;
     private BigDecimal othplantestdefect;
     private BigDecimal othreplantestdefect;
     private Blob schedulefile;
     private String schedulefilename;
     private BigDecimal planCalendarEffort;
     private BigDecimal replanCalendarEffort;
     private Byte contractType;
     private String reqnotereviewdefect;
     private String desnotereviewdefect;
     private String codnotereviewdefect;
     private String reqnotetestdefect;
     private String desnotetestdefect;
     private String codnotetestdefect;
     private Clob proposal;
     private Set constraintses = new HashSet(0);
     private Set referenceses = new HashSet(0);
     private Set interfaces = new HashSet(0);

    public ProjectPlan() {
    }

	
    public ProjectPlan(BigDecimal projectPlanId) {
        this.projectPlanId = projectPlanId;
    }
    public ProjectPlan(BigDecimal projectPlanId, Project project, ApplicationType applicationType, Date lastUpdate, BigDecimal managementEffort, BigDecimal qualityEffort, String schedule, Clob structure, Clob projectCommunication, Clob managementCommunication, Clob customerCommunication, Clob otherCommunication, Clob qualityObjectiveStrategy, String configurationManagement, BigDecimal maxTeamSize, BigDecimal timeliness, String customerLocation, String domain, String director, Clob scopeObjective, Clob asset, Clob problem, Clob rewardPenalty, Clob orgStructure, BigDecimal reqplanreviewdefect, BigDecimal reqreplanreviewdefect, BigDecimal desplanreviewdefect, BigDecimal desreplanreviewdefect, BigDecimal codplanreviewdefect, BigDecimal codreplanreviewdefect, BigDecimal othplanreviewdefect, BigDecimal othreplanreviewdefect, BigDecimal reqplantestdefect, BigDecimal reqreplantestdefect, BigDecimal desplantestdefect, BigDecimal desreplantestdefect, BigDecimal codplantestdefect, BigDecimal codreplantestdefect, BigDecimal othplantestdefect, BigDecimal othreplantestdefect, Blob schedulefile, String schedulefilename, BigDecimal planCalendarEffort, BigDecimal replanCalendarEffort, Byte contractType, String reqnotereviewdefect, String desnotereviewdefect, String codnotereviewdefect, String reqnotetestdefect, String desnotetestdefect, String codnotetestdefect, Clob proposal, Set constraintses, Set referenceses, Set interfaces) {
       this.projectPlanId = projectPlanId;
       this.project = project;
       this.applicationType = applicationType;
       this.lastUpdate = lastUpdate;
       this.managementEffort = managementEffort;
       this.qualityEffort = qualityEffort;
       this.schedule = schedule;
       this.structure = structure;
       this.projectCommunication = projectCommunication;
       this.managementCommunication = managementCommunication;
       this.customerCommunication = customerCommunication;
       this.otherCommunication = otherCommunication;
       this.qualityObjectiveStrategy = qualityObjectiveStrategy;
       this.configurationManagement = configurationManagement;
       this.maxTeamSize = maxTeamSize;
       this.timeliness = timeliness;
       this.customerLocation = customerLocation;
       this.domain = domain;
       this.director = director;
       this.scopeObjective = scopeObjective;
       this.asset = asset;
       this.problem = problem;
       this.rewardPenalty = rewardPenalty;
       this.orgStructure = orgStructure;
       this.reqplanreviewdefect = reqplanreviewdefect;
       this.reqreplanreviewdefect = reqreplanreviewdefect;
       this.desplanreviewdefect = desplanreviewdefect;
       this.desreplanreviewdefect = desreplanreviewdefect;
       this.codplanreviewdefect = codplanreviewdefect;
       this.codreplanreviewdefect = codreplanreviewdefect;
       this.othplanreviewdefect = othplanreviewdefect;
       this.othreplanreviewdefect = othreplanreviewdefect;
       this.reqplantestdefect = reqplantestdefect;
       this.reqreplantestdefect = reqreplantestdefect;
       this.desplantestdefect = desplantestdefect;
       this.desreplantestdefect = desreplantestdefect;
       this.codplantestdefect = codplantestdefect;
       this.codreplantestdefect = codreplantestdefect;
       this.othplantestdefect = othplantestdefect;
       this.othreplantestdefect = othreplantestdefect;
       this.schedulefile = schedulefile;
       this.schedulefilename = schedulefilename;
       this.planCalendarEffort = planCalendarEffort;
       this.replanCalendarEffort = replanCalendarEffort;
       this.contractType = contractType;
       this.reqnotereviewdefect = reqnotereviewdefect;
       this.desnotereviewdefect = desnotereviewdefect;
       this.codnotereviewdefect = codnotereviewdefect;
       this.reqnotetestdefect = reqnotetestdefect;
       this.desnotetestdefect = desnotetestdefect;
       this.codnotetestdefect = codnotetestdefect;
       this.proposal = proposal;
       this.constraintses = constraintses;
       this.referenceses = referenceses;
       this.interfaces = interfaces;
    }
   
    public BigDecimal getProjectPlanId() {
        return this.projectPlanId;
    }
    
    public void setProjectPlanId(BigDecimal projectPlanId) {
        this.projectPlanId = projectPlanId;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public ApplicationType getApplicationType() {
        return this.applicationType;
    }
    
    public void setApplicationType(ApplicationType applicationType) {
        this.applicationType = applicationType;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public BigDecimal getManagementEffort() {
        return this.managementEffort;
    }
    
    public void setManagementEffort(BigDecimal managementEffort) {
        this.managementEffort = managementEffort;
    }
    public BigDecimal getQualityEffort() {
        return this.qualityEffort;
    }
    
    public void setQualityEffort(BigDecimal qualityEffort) {
        this.qualityEffort = qualityEffort;
    }
    public String getSchedule() {
        return this.schedule;
    }
    
    public void setSchedule(String schedule) {
        this.schedule = schedule;
    }
    public Clob getStructure() {
        return this.structure;
    }
    
    public void setStructure(Clob structure) {
        this.structure = structure;
    }
    public Clob getProjectCommunication() {
        return this.projectCommunication;
    }
    
    public void setProjectCommunication(Clob projectCommunication) {
        this.projectCommunication = projectCommunication;
    }
    public Clob getManagementCommunication() {
        return this.managementCommunication;
    }
    
    public void setManagementCommunication(Clob managementCommunication) {
        this.managementCommunication = managementCommunication;
    }
    public Clob getCustomerCommunication() {
        return this.customerCommunication;
    }
    
    public void setCustomerCommunication(Clob customerCommunication) {
        this.customerCommunication = customerCommunication;
    }
    public Clob getOtherCommunication() {
        return this.otherCommunication;
    }
    
    public void setOtherCommunication(Clob otherCommunication) {
        this.otherCommunication = otherCommunication;
    }
    public Clob getQualityObjectiveStrategy() {
        return this.qualityObjectiveStrategy;
    }
    
    public void setQualityObjectiveStrategy(Clob qualityObjectiveStrategy) {
        this.qualityObjectiveStrategy = qualityObjectiveStrategy;
    }
    public String getConfigurationManagement() {
        return this.configurationManagement;
    }
    
    public void setConfigurationManagement(String configurationManagement) {
        this.configurationManagement = configurationManagement;
    }
    public BigDecimal getMaxTeamSize() {
        return this.maxTeamSize;
    }
    
    public void setMaxTeamSize(BigDecimal maxTeamSize) {
        this.maxTeamSize = maxTeamSize;
    }
    public BigDecimal getTimeliness() {
        return this.timeliness;
    }
    
    public void setTimeliness(BigDecimal timeliness) {
        this.timeliness = timeliness;
    }
    public String getCustomerLocation() {
        return this.customerLocation;
    }
    
    public void setCustomerLocation(String customerLocation) {
        this.customerLocation = customerLocation;
    }
    public String getDomain() {
        return this.domain;
    }
    
    public void setDomain(String domain) {
        this.domain = domain;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public Clob getScopeObjective() {
        return this.scopeObjective;
    }
    
    public void setScopeObjective(Clob scopeObjective) {
        this.scopeObjective = scopeObjective;
    }
    public Clob getAsset() {
        return this.asset;
    }
    
    public void setAsset(Clob asset) {
        this.asset = asset;
    }
    public Clob getProblem() {
        return this.problem;
    }
    
    public void setProblem(Clob problem) {
        this.problem = problem;
    }
    public Clob getRewardPenalty() {
        return this.rewardPenalty;
    }
    
    public void setRewardPenalty(Clob rewardPenalty) {
        this.rewardPenalty = rewardPenalty;
    }
    public Clob getOrgStructure() {
        return this.orgStructure;
    }
    
    public void setOrgStructure(Clob orgStructure) {
        this.orgStructure = orgStructure;
    }
    public BigDecimal getReqplanreviewdefect() {
        return this.reqplanreviewdefect;
    }
    
    public void setReqplanreviewdefect(BigDecimal reqplanreviewdefect) {
        this.reqplanreviewdefect = reqplanreviewdefect;
    }
    public BigDecimal getReqreplanreviewdefect() {
        return this.reqreplanreviewdefect;
    }
    
    public void setReqreplanreviewdefect(BigDecimal reqreplanreviewdefect) {
        this.reqreplanreviewdefect = reqreplanreviewdefect;
    }
    public BigDecimal getDesplanreviewdefect() {
        return this.desplanreviewdefect;
    }
    
    public void setDesplanreviewdefect(BigDecimal desplanreviewdefect) {
        this.desplanreviewdefect = desplanreviewdefect;
    }
    public BigDecimal getDesreplanreviewdefect() {
        return this.desreplanreviewdefect;
    }
    
    public void setDesreplanreviewdefect(BigDecimal desreplanreviewdefect) {
        this.desreplanreviewdefect = desreplanreviewdefect;
    }
    public BigDecimal getCodplanreviewdefect() {
        return this.codplanreviewdefect;
    }
    
    public void setCodplanreviewdefect(BigDecimal codplanreviewdefect) {
        this.codplanreviewdefect = codplanreviewdefect;
    }
    public BigDecimal getCodreplanreviewdefect() {
        return this.codreplanreviewdefect;
    }
    
    public void setCodreplanreviewdefect(BigDecimal codreplanreviewdefect) {
        this.codreplanreviewdefect = codreplanreviewdefect;
    }
    public BigDecimal getOthplanreviewdefect() {
        return this.othplanreviewdefect;
    }
    
    public void setOthplanreviewdefect(BigDecimal othplanreviewdefect) {
        this.othplanreviewdefect = othplanreviewdefect;
    }
    public BigDecimal getOthreplanreviewdefect() {
        return this.othreplanreviewdefect;
    }
    
    public void setOthreplanreviewdefect(BigDecimal othreplanreviewdefect) {
        this.othreplanreviewdefect = othreplanreviewdefect;
    }
    public BigDecimal getReqplantestdefect() {
        return this.reqplantestdefect;
    }
    
    public void setReqplantestdefect(BigDecimal reqplantestdefect) {
        this.reqplantestdefect = reqplantestdefect;
    }
    public BigDecimal getReqreplantestdefect() {
        return this.reqreplantestdefect;
    }
    
    public void setReqreplantestdefect(BigDecimal reqreplantestdefect) {
        this.reqreplantestdefect = reqreplantestdefect;
    }
    public BigDecimal getDesplantestdefect() {
        return this.desplantestdefect;
    }
    
    public void setDesplantestdefect(BigDecimal desplantestdefect) {
        this.desplantestdefect = desplantestdefect;
    }
    public BigDecimal getDesreplantestdefect() {
        return this.desreplantestdefect;
    }
    
    public void setDesreplantestdefect(BigDecimal desreplantestdefect) {
        this.desreplantestdefect = desreplantestdefect;
    }
    public BigDecimal getCodplantestdefect() {
        return this.codplantestdefect;
    }
    
    public void setCodplantestdefect(BigDecimal codplantestdefect) {
        this.codplantestdefect = codplantestdefect;
    }
    public BigDecimal getCodreplantestdefect() {
        return this.codreplantestdefect;
    }
    
    public void setCodreplantestdefect(BigDecimal codreplantestdefect) {
        this.codreplantestdefect = codreplantestdefect;
    }
    public BigDecimal getOthplantestdefect() {
        return this.othplantestdefect;
    }
    
    public void setOthplantestdefect(BigDecimal othplantestdefect) {
        this.othplantestdefect = othplantestdefect;
    }
    public BigDecimal getOthreplantestdefect() {
        return this.othreplantestdefect;
    }
    
    public void setOthreplantestdefect(BigDecimal othreplantestdefect) {
        this.othreplantestdefect = othreplantestdefect;
    }
    public Blob getSchedulefile() {
        return this.schedulefile;
    }
    
    public void setSchedulefile(Blob schedulefile) {
        this.schedulefile = schedulefile;
    }
    public String getSchedulefilename() {
        return this.schedulefilename;
    }
    
    public void setSchedulefilename(String schedulefilename) {
        this.schedulefilename = schedulefilename;
    }
    public BigDecimal getPlanCalendarEffort() {
        return this.planCalendarEffort;
    }
    
    public void setPlanCalendarEffort(BigDecimal planCalendarEffort) {
        this.planCalendarEffort = planCalendarEffort;
    }
    public BigDecimal getReplanCalendarEffort() {
        return this.replanCalendarEffort;
    }
    
    public void setReplanCalendarEffort(BigDecimal replanCalendarEffort) {
        this.replanCalendarEffort = replanCalendarEffort;
    }
    public Byte getContractType() {
        return this.contractType;
    }
    
    public void setContractType(Byte contractType) {
        this.contractType = contractType;
    }
    public String getReqnotereviewdefect() {
        return this.reqnotereviewdefect;
    }
    
    public void setReqnotereviewdefect(String reqnotereviewdefect) {
        this.reqnotereviewdefect = reqnotereviewdefect;
    }
    public String getDesnotereviewdefect() {
        return this.desnotereviewdefect;
    }
    
    public void setDesnotereviewdefect(String desnotereviewdefect) {
        this.desnotereviewdefect = desnotereviewdefect;
    }
    public String getCodnotereviewdefect() {
        return this.codnotereviewdefect;
    }
    
    public void setCodnotereviewdefect(String codnotereviewdefect) {
        this.codnotereviewdefect = codnotereviewdefect;
    }
    public String getReqnotetestdefect() {
        return this.reqnotetestdefect;
    }
    
    public void setReqnotetestdefect(String reqnotetestdefect) {
        this.reqnotetestdefect = reqnotetestdefect;
    }
    public String getDesnotetestdefect() {
        return this.desnotetestdefect;
    }
    
    public void setDesnotetestdefect(String desnotetestdefect) {
        this.desnotetestdefect = desnotetestdefect;
    }
    public String getCodnotetestdefect() {
        return this.codnotetestdefect;
    }
    
    public void setCodnotetestdefect(String codnotetestdefect) {
        this.codnotetestdefect = codnotetestdefect;
    }
    public Clob getProposal() {
        return this.proposal;
    }
    
    public void setProposal(Clob proposal) {
        this.proposal = proposal;
    }
    public Set getConstraintses() {
        return this.constraintses;
    }
    
    public void setConstraintses(Set constraintses) {
        this.constraintses = constraintses;
    }
    public Set getReferenceses() {
        return this.referenceses;
    }
    
    public void setReferenceses(Set referenceses) {
        this.referenceses = referenceses;
    }
    public Set getInterfaces() {
        return this.interfaces;
    }
    
    public void setInterfaces(Set interfaces) {
        this.interfaces = interfaces;
    }




}


