package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ProjectTailoringId generated by hbm2java
 */
public class ProjectTailoringId  implements java.io.Serializable {


     private BigDecimal projectId;
     private BigDecimal processTailId;

    public ProjectTailoringId() {
    }

    public ProjectTailoringId(BigDecimal projectId, BigDecimal processTailId) {
       this.projectId = projectId;
       this.processTailId = processTailId;
    }
   
    public BigDecimal getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(BigDecimal projectId) {
        this.projectId = projectId;
    }
    public BigDecimal getProcessTailId() {
        return this.processTailId;
    }
    
    public void setProcessTailId(BigDecimal processTailId) {
        this.processTailId = processTailId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProjectTailoringId) ) return false;
		 ProjectTailoringId castOther = ( ProjectTailoringId ) other; 
         
		 return ( (this.getProjectId()==castOther.getProjectId()) || ( this.getProjectId()!=null && castOther.getProjectId()!=null && this.getProjectId().equals(castOther.getProjectId()) ) )
 && ( (this.getProcessTailId()==castOther.getProcessTailId()) || ( this.getProcessTailId()!=null && castOther.getProcessTailId()!=null && this.getProcessTailId().equals(castOther.getProcessTailId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProjectId() == null ? 0 : this.getProjectId().hashCode() );
         result = 37 * result + ( getProcessTailId() == null ? 0 : this.getProcessTailId().hashCode() );
         return result;
   }   


}


