package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * QcActivity generated by hbm2java
 */
public class QcActivity  implements java.io.Serializable {


     private String code;
     private String name;
     private BigDecimal qaId;
     private Short orderNumber;
     private Byte disabled;
     private String appName;
     private Set processes = new HashSet(0);
     private Set activityTypes = new HashSet(0);
     private Set workproducts = new HashSet(0);

    public QcActivity() {
    }

	
    public QcActivity(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public QcActivity(String code, String name, BigDecimal qaId, Short orderNumber, Byte disabled, String appName, Set processes, Set activityTypes, Set workproducts) {
       this.code = code;
       this.name = name;
       this.qaId = qaId;
       this.orderNumber = orderNumber;
       this.disabled = disabled;
       this.appName = appName;
       this.processes = processes;
       this.activityTypes = activityTypes;
       this.workproducts = workproducts;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getQaId() {
        return this.qaId;
    }
    
    public void setQaId(BigDecimal qaId) {
        this.qaId = qaId;
    }
    public Short getOrderNumber() {
        return this.orderNumber;
    }
    
    public void setOrderNumber(Short orderNumber) {
        this.orderNumber = orderNumber;
    }
    public Byte getDisabled() {
        return this.disabled;
    }
    
    public void setDisabled(Byte disabled) {
        this.disabled = disabled;
    }
    public String getAppName() {
        return this.appName;
    }
    
    public void setAppName(String appName) {
        this.appName = appName;
    }
    public Set getProcesses() {
        return this.processes;
    }
    
    public void setProcesses(Set processes) {
        this.processes = processes;
    }
    public Set getActivityTypes() {
        return this.activityTypes;
    }
    
    public void setActivityTypes(Set activityTypes) {
        this.activityTypes = activityTypes;
    }
    public Set getWorkproducts() {
        return this.workproducts;
    }
    
    public void setWorkproducts(Set workproducts) {
        this.workproducts = workproducts;
    }




}


