package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ReviewStrategy generated by hbm2java
 */
public class ReviewStrategy  implements java.io.Serializable {


     private BigDecimal revId;
     private BigDecimal revPrjId;
     private String revType;
     private String revItem;
     private String revReviewer;
     private String revWhen;

    public ReviewStrategy() {
    }

	
    public ReviewStrategy(BigDecimal revId, BigDecimal revPrjId) {
        this.revId = revId;
        this.revPrjId = revPrjId;
    }
    public ReviewStrategy(BigDecimal revId, BigDecimal revPrjId, String revType, String revItem, String revReviewer, String revWhen) {
       this.revId = revId;
       this.revPrjId = revPrjId;
       this.revType = revType;
       this.revItem = revItem;
       this.revReviewer = revReviewer;
       this.revWhen = revWhen;
    }
   
    public BigDecimal getRevId() {
        return this.revId;
    }
    
    public void setRevId(BigDecimal revId) {
        this.revId = revId;
    }
    public BigDecimal getRevPrjId() {
        return this.revPrjId;
    }
    
    public void setRevPrjId(BigDecimal revPrjId) {
        this.revPrjId = revPrjId;
    }
    public String getRevType() {
        return this.revType;
    }
    
    public void setRevType(String revType) {
        this.revType = revType;
    }
    public String getRevItem() {
        return this.revItem;
    }
    
    public void setRevItem(String revItem) {
        this.revItem = revItem;
    }
    public String getRevReviewer() {
        return this.revReviewer;
    }
    
    public void setRevReviewer(String revReviewer) {
        this.revReviewer = revReviewer;
    }
    public String getRevWhen() {
        return this.revWhen;
    }
    
    public void setRevWhen(String revWhen) {
        this.revWhen = revWhen;
    }




}


