package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Subcontract generated by hbm2java
 */
public class Subcontract  implements java.io.Serializable {


     private BigDecimal subcontractId;
     private Project project;
     private String deliverable;
     private Date planDeliveryDate;
     private Date actualDeliveryDate;
     private String job;
     private String note;
     private String sname;
     private String contactPerson;
     private String refToContract;

    public Subcontract() {
    }

	
    public Subcontract(BigDecimal subcontractId) {
        this.subcontractId = subcontractId;
    }
    public Subcontract(BigDecimal subcontractId, Project project, String deliverable, Date planDeliveryDate, Date actualDeliveryDate, String job, String note, String sname, String contactPerson, String refToContract) {
       this.subcontractId = subcontractId;
       this.project = project;
       this.deliverable = deliverable;
       this.planDeliveryDate = planDeliveryDate;
       this.actualDeliveryDate = actualDeliveryDate;
       this.job = job;
       this.note = note;
       this.sname = sname;
       this.contactPerson = contactPerson;
       this.refToContract = refToContract;
    }
   
    public BigDecimal getSubcontractId() {
        return this.subcontractId;
    }
    
    public void setSubcontractId(BigDecimal subcontractId) {
        this.subcontractId = subcontractId;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public String getDeliverable() {
        return this.deliverable;
    }
    
    public void setDeliverable(String deliverable) {
        this.deliverable = deliverable;
    }
    public Date getPlanDeliveryDate() {
        return this.planDeliveryDate;
    }
    
    public void setPlanDeliveryDate(Date planDeliveryDate) {
        this.planDeliveryDate = planDeliveryDate;
    }
    public Date getActualDeliveryDate() {
        return this.actualDeliveryDate;
    }
    
    public void setActualDeliveryDate(Date actualDeliveryDate) {
        this.actualDeliveryDate = actualDeliveryDate;
    }
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getContactPerson() {
        return this.contactPerson;
    }
    
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }
    public String getRefToContract() {
        return this.refToContract;
    }
    
    public void setRefToContract(String refToContract) {
        this.refToContract = refToContract;
    }




}


