package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Tools generated by hbm2java
 */
public class Tools  implements java.io.Serializable {


     private BigDecimal toolId;
     private Project project;
     private String name;
     private String purpose;
     private String source;
     private String description;
     private String status;
     private Date dueDate;
     private Date actualDate;
     private String note;
     private Byte toolType;
     private String expectedAvailabilityStage;
     private String actualAvailabilityStage;

    public Tools() {
    }

	
    public Tools(BigDecimal toolId) {
        this.toolId = toolId;
    }
    public Tools(BigDecimal toolId, Project project, String name, String purpose, String source, String description, String status, Date dueDate, Date actualDate, String note, Byte toolType, String expectedAvailabilityStage, String actualAvailabilityStage) {
       this.toolId = toolId;
       this.project = project;
       this.name = name;
       this.purpose = purpose;
       this.source = source;
       this.description = description;
       this.status = status;
       this.dueDate = dueDate;
       this.actualDate = actualDate;
       this.note = note;
       this.toolType = toolType;
       this.expectedAvailabilityStage = expectedAvailabilityStage;
       this.actualAvailabilityStage = actualAvailabilityStage;
    }
   
    public BigDecimal getToolId() {
        return this.toolId;
    }
    
    public void setToolId(BigDecimal toolId) {
        this.toolId = toolId;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPurpose() {
        return this.purpose;
    }
    
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public Date getActualDate() {
        return this.actualDate;
    }
    
    public void setActualDate(Date actualDate) {
        this.actualDate = actualDate;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Byte getToolType() {
        return this.toolType;
    }
    
    public void setToolType(Byte toolType) {
        this.toolType = toolType;
    }
    public String getExpectedAvailabilityStage() {
        return this.expectedAvailabilityStage;
    }
    
    public void setExpectedAvailabilityStage(String expectedAvailabilityStage) {
        this.expectedAvailabilityStage = expectedAvailabilityStage;
    }
    public String getActualAvailabilityStage() {
        return this.actualAvailabilityStage;
    }
    
    public void setActualAvailabilityStage(String actualAvailabilityStage) {
        this.actualAvailabilityStage = actualAvailabilityStage;
    }




}


