package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * WpSize generated by hbm2java
 */
public class WpSize  implements java.io.Serializable {


     private WpSizeId id;
     private ApSizeunit apSizeunit;
     private BigDecimal wpSize;
     private BigDecimal plannedDefect;
     private BigDecimal replannedDefect;

    public WpSize() {
    }

	
    public WpSize(WpSizeId id) {
        this.id = id;
    }
    public WpSize(WpSizeId id, ApSizeunit apSizeunit, BigDecimal wpSize, BigDecimal plannedDefect, BigDecimal replannedDefect) {
       this.id = id;
       this.apSizeunit = apSizeunit;
       this.wpSize = wpSize;
       this.plannedDefect = plannedDefect;
       this.replannedDefect = replannedDefect;
    }
   
    public WpSizeId getId() {
        return this.id;
    }
    
    public void setId(WpSizeId id) {
        this.id = id;
    }
    public ApSizeunit getApSizeunit() {
        return this.apSizeunit;
    }
    
    public void setApSizeunit(ApSizeunit apSizeunit) {
        this.apSizeunit = apSizeunit;
    }
    public BigDecimal getWpSize() {
        return this.wpSize;
    }
    
    public void setWpSize(BigDecimal wpSize) {
        this.wpSize = wpSize;
    }
    public BigDecimal getPlannedDefect() {
        return this.plannedDefect;
    }
    
    public void setPlannedDefect(BigDecimal plannedDefect) {
        this.plannedDefect = plannedDefect;
    }
    public BigDecimal getReplannedDefect() {
        return this.replannedDefect;
    }
    
    public void setReplannedDefect(BigDecimal replannedDefect) {
        this.replannedDefect = replannedDefect;
    }




}


