package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * FurtherWork generated by hbm2java
 */
public class FurtherWork  implements java.io.Serializable {


     private BigDecimal furtherWorkId;
     private Project project;
     private String name;
     private String result;
     private BigDecimal time;
     private String responsibility;
     private String note;

    public FurtherWork() {
    }

	
    public FurtherWork(BigDecimal furtherWorkId) {
        this.furtherWorkId = furtherWorkId;
    }
    public FurtherWork(BigDecimal furtherWorkId, Project project, String name, String result, BigDecimal time, String responsibility, String note) {
       this.furtherWorkId = furtherWorkId;
       this.project = project;
       this.name = name;
       this.result = result;
       this.time = time;
       this.responsibility = responsibility;
       this.note = note;
    }
   
    public BigDecimal getFurtherWorkId() {
        return this.furtherWorkId;
    }
    
    public void setFurtherWorkId(BigDecimal furtherWorkId) {
        this.furtherWorkId = furtherWorkId;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    public BigDecimal getTime() {
        return this.time;
    }
    
    public void setTime(BigDecimal time) {
        this.time = time;
    }
    public String getResponsibility() {
        return this.responsibility;
    }
    
    public void setResponsibility(String responsibility) {
        this.responsibility = responsibility;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


