package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA



/**
 * Rightgroup generated by hbm2java
 */
public class Rightgroup  implements java.io.Serializable {


     private String rightgroupid;
     private String mnglevel;
     private String description;
     private Boolean protected_;

    public Rightgroup() {
    }

	
    public Rightgroup(String rightgroupid, String mnglevel) {
        this.rightgroupid = rightgroupid;
        this.mnglevel = mnglevel;
    }
    public Rightgroup(String rightgroupid, String mnglevel, String description, Boolean protected_) {
       this.rightgroupid = rightgroupid;
       this.mnglevel = mnglevel;
       this.description = description;
       this.protected_ = protected_;
    }
   
    public String getRightgroupid() {
        return this.rightgroupid;
    }
    
    public void setRightgroupid(String rightgroupid) {
        this.rightgroupid = rightgroupid;
    }
    public String getMnglevel() {
        return this.mnglevel;
    }
    
    public void setMnglevel(String mnglevel) {
        this.mnglevel = mnglevel;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Boolean getProtected_() {
        return this.protected_;
    }
    
    public void setProtected_(Boolean protected_) {
        this.protected_ = protected_;
    }




}


