package openones.oopms.entity;
// Generated 12:18:17 01-03-2012 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Team generated by hbm2java
 */
public class Team  implements java.io.Serializable {


     private BigDecimal teamId;
     private Developer developer;
     private String teamName;
     private BigDecimal parentTeamId;
     private String note;
     private Set assignments = new HashSet(0);

    public Team() {
    }

	
    public Team(BigDecimal teamId, String teamName) {
        this.teamId = teamId;
        this.teamName = teamName;
    }
    public Team(BigDecimal teamId, Developer developer, String teamName, BigDecimal parentTeamId, String note, Set assignments) {
       this.teamId = teamId;
       this.developer = developer;
       this.teamName = teamName;
       this.parentTeamId = parentTeamId;
       this.note = note;
       this.assignments = assignments;
    }
   
    public BigDecimal getTeamId() {
        return this.teamId;
    }
    
    public void setTeamId(BigDecimal teamId) {
        this.teamId = teamId;
    }
    public Developer getDeveloper() {
        return this.developer;
    }
    
    public void setDeveloper(Developer developer) {
        this.developer = developer;
    }
    public String getTeamName() {
        return this.teamName;
    }
    
    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }
    public BigDecimal getParentTeamId() {
        return this.parentTeamId;
    }
    
    public void setParentTeamId(BigDecimal parentTeamId) {
        this.parentTeamId = parentTeamId;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Set getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(Set assignments) {
        this.assignments = assignments;
    }




}


