package openones.oopms.model;
// Generated Jul 9, 2012 10:54:25 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * OopmsTask generated by hbm2java
 */
public class OopmsTask  implements java.io.Serializable {


     private long taskid;
     private String taskcode;
     private String taskname;
     private long status;
     private long assignmentid;
     private long stageid;
     private long product;
     private long productsize;
     private long completenessstatus;
     private Date startdate;
     private Date plannedenddate;
     private Date enddate;
     private long plannedeffort;
     private long actualeffort;
     private String description;
     private long projectid;
     private Boolean active;

    public OopmsTask() {
    }

	
    public OopmsTask(long taskid) {
        this.taskid = taskid;
    }
    public OopmsTask(long taskid, String taskcode, String taskname, long status, long assignmentid, long stageid, long product, long productsize, long completenessstatus, Date startdate, Date plannedenddate, Date enddate, long plannedeffort, long actualeffort, String description, long projectid, Boolean active) {
       this.taskid = taskid;
       this.taskcode = taskcode;
       this.taskname = taskname;
       this.status = status;
       this.assignmentid = assignmentid;
       this.stageid = stageid;
       this.product = product;
       this.productsize = productsize;
       this.completenessstatus = completenessstatus;
       this.startdate = startdate;
       this.plannedenddate = plannedenddate;
       this.enddate = enddate;
       this.plannedeffort = plannedeffort;
       this.actualeffort = actualeffort;
       this.description = description;
       this.projectid = projectid;
       this.active = active;
    }
   
    public long getTaskid() {
        return this.taskid;
    }
    
    public void setTaskid(long taskid) {
        this.taskid = taskid;
    }
    public String getTaskcode() {
        return this.taskcode;
    }
    
    public void setTaskcode(String taskcode) {
        this.taskcode = taskcode;
    }
    public String getTaskname() {
        return this.taskname;
    }
    
    public void setTaskname(String taskname) {
        this.taskname = taskname;
    }
    public long getStatus() {
        return this.status;
    }
    
    public void setStatus(long status) {
        this.status = status;
    }
    public long getAssignmentid() {
        return this.assignmentid;
    }
    
    public void setAssignmentid(long assignmentid) {
        this.assignmentid = assignmentid;
    }
    public long getStageid() {
        return this.stageid;
    }
    
    public void setStageid(long stageid) {
        this.stageid = stageid;
    }
    public long getProduct() {
        return this.product;
    }
    
    public void setProduct(long product) {
        this.product = product;
    }
    public long getProductsize() {
        return this.productsize;
    }
    
    public void setProductsize(long productsize) {
        this.productsize = productsize;
    }
    public long getCompletenessstatus() {
        return this.completenessstatus;
    }
    
    public void setCompletenessstatus(long completenessstatus) {
        this.completenessstatus = completenessstatus;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getPlannedenddate() {
        return this.plannedenddate;
    }
    
    public void setPlannedenddate(Date plannedenddate) {
        this.plannedenddate = plannedenddate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public long getPlannedeffort() {
        return this.plannedeffort;
    }
    
    public void setPlannedeffort(long plannedeffort) {
        this.plannedeffort = plannedeffort;
    }
    public long getActualeffort() {
        return this.actualeffort;
    }
    
    public void setActualeffort(long actualeffort) {
        this.actualeffort = actualeffort;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public long getProjectid() {
        return this.projectid;
    }
    
    public void setProjectid(long projectid) {
        this.projectid = projectid;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }




}


