package openones.oopms.model;
// Generated Jul 9, 2012 10:54:25 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * OopmsTask generated by hbm2java
 */
public class OopmsTask  implements java.io.Serializable {


     private BigDecimal taskid;
     private String taskcode;
     private String taskname;
     private BigDecimal status;
     private String status_str;
     private BigDecimal assignmentid;
     private BigDecimal stageid;
     private String stage_str;
     private BigDecimal product;
     private String product_str;
     private BigDecimal productsize;
     private BigDecimal completenessstatus;
     private Date startdate;
     private Date plannedenddate;
     private Date enddate;
     private BigDecimal plannedeffort;
     private BigDecimal actualeffort;
     private String description;
     private BigDecimal projectid;
     private Boolean active;

    public OopmsTask() {
    }

	
    public OopmsTask(BigDecimal taskid) {
        this.taskid = taskid;
    }
    public OopmsTask(BigDecimal taskid, String taskcode, String taskname, BigDecimal status, BigDecimal assignmentid, BigDecimal stageid, BigDecimal product, BigDecimal productsize, BigDecimal completenessstatus, Date startdate, Date plannedenddate, Date enddate, BigDecimal plannedeffort, BigDecimal actualeffort, String description, BigDecimal projectid, Boolean active) {
       this.taskid = taskid;
       this.taskcode = taskcode;
       this.taskname = taskname;
       this.status = status;
       this.assignmentid = assignmentid;
       this.stageid = stageid;
       this.product = product;
       this.productsize = productsize;
       this.completenessstatus = completenessstatus;
       this.startdate = startdate;
       this.plannedenddate = plannedenddate;
       this.enddate = enddate;
       this.plannedeffort = plannedeffort;
       this.actualeffort = actualeffort;
       this.description = description;
       this.projectid = projectid;
       this.active = active;
    }
   
    public BigDecimal getTaskid() {
        return this.taskid;
    }
    
    public void setTaskid(BigDecimal taskid) {
        this.taskid = taskid;
    }
    public String getTaskcode() {
        return this.taskcode;
    }
    
    public void setTaskcode(String taskcode) {
        this.taskcode = taskcode;
    }
    public String getTaskname() {
        return this.taskname;
    }
    
    public void setTaskname(String taskname) {
        this.taskname = taskname;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public BigDecimal getAssignmentid() {
        return this.assignmentid;
    }
    
    public void setAssignmentid(BigDecimal assignmentid) {
        this.assignmentid = assignmentid;
    }
    public BigDecimal getStageid() {
        return this.stageid;
    }
    
    public void setStageid(BigDecimal stageid) {
        this.stageid = stageid;
    }
    public BigDecimal getProduct() {
        return this.product;
    }
    
    public void setProduct(BigDecimal product) {
        this.product = product;
    }
    public BigDecimal getProductsize() {
        return this.productsize;
    }
    
    public void setProductsize(BigDecimal productsize) {
        this.productsize = productsize;
    }
    public BigDecimal getCompletenessstatus() {
        return this.completenessstatus;
    }
    
    public void setCompletenessstatus(BigDecimal completenessstatus) {
        this.completenessstatus = completenessstatus;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getPlannedenddate() {
        return this.plannedenddate;
    }
    
    public void setPlannedenddate(Date plannedenddate) {
        this.plannedenddate = plannedenddate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public BigDecimal getPlannedeffort() {
        return this.plannedeffort;
    }
    
    public void setPlannedeffort(BigDecimal plannedeffort) {
        this.plannedeffort = plannedeffort;
    }
    public BigDecimal getActualeffort() {
        return this.actualeffort;
    }
    
    public void setActualeffort(BigDecimal actualeffort) {
        this.actualeffort = actualeffort;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getProjectid() {
        return this.projectid;
    }
    
    public void setProjectid(BigDecimal projectid) {
        this.projectid = projectid;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }




}


